/***************************************************************************
                          rrc_rb_ue.h  -  description
                             -------------------
    begin                : April 26, 2002
    copyright            : (C) 2002, 2010 by Eurecom
    email                : Michelle.Wetterwald@eurecom.fr
 **************************************************************************
  Header associated with the rrc_rb_ue.c file generated by Esterel Studio
 ***************************************************************************/
#include  "rrc_constant.h"


/* Generic function to encode RRC messages */
void  encode_message (int *Message_Id, int Message_Type);

int   INTEGER_COMBINE (int Id1, int Id2);
int   BOOLEAN_COMBINE (int Id1, int Id2);

/* Selection of channels during RRC Connection SetUp
 */
void  Select_PRACH (void);
void  Select_Secondary_CCPCH (void);

/* Record of current RRC state - to be stored in: protocol_ms->rrc.protocol_state
 */
void  Set_State (int new_state);

/* release resources in RLC, MAC, PHY (no reply)
 */
void  release_radio_resources (void);

/* clear RRC variables: TRANSACTIONS, ESTABLISHED_SIGNALLING_CONNECTIONS, ESTABLISHED_RBs...
 */
void  clear_variables_rel (void);


/* function prototypes for the RRC Radio Bearer Establishment and Release procedures, UE side */
void  proc_IE_activ_Time (void);
void  proc_IE_RNTIs (void);
void  proc_IE_transaction (void);
void  proc_IE_configuration (void);
void  clear_C_RNTI (void);
void  set_RRC_Transaction_ID (void);
/* clear RRC TRANSACTIONS IDENTIFIER...
 */
void  ue_clear_transaction (int Message_Type);
