/***************************************************************************
                          rrc_rg.h  -  description
                             -------------------
    begin                : May 22, 2002
    copyright            : (C) 2002, 2010 by Eurecom
    email                : Michelle.Wetterwald@eurecom.fr
 **************************************************************************
  Header associated with the rrc_rg.c file generated by Esterel Studio
 ***************************************************************************/
#include  "rrc_constant.h"

/* Generic function to encode RRC messages
 */
void encode_message (int *Message_Id, int UE_Id, int Message_Type);

/* Utility functions
 */
int Current_State (int UE_Id);
int INTEGER_COMBINE (int Id1, int Id2);
int BOOLEAN_COMBINE (int Id1, int Id2);

/* Management of Mobile Nodes
 */
void create_Mobile (int UE_Id);
void update_Mobile (int UE_Id, int new_state);
void delete_Mobile (int UE_Id);

/* Other processes
 */
void proc_RB_List(int *Message_Id, int RB_List, int UE_Id);
void release_DCH_Resources(int UE_Id);
void restore_former_config(int UE_Id);
void rg_clear_transaction (int UE_Id, int Message_Type);
void clear_rbsetup_variables(int UE_Id);
void clear_rbrelease_variables(int UE_Id);
void rg_update_UE_numrb(int UE_Id, int Action);
