/***************************************************************************
                            rrc_rg.c
                           -------------------
    begin                : May 31, 2002
    copyright            : (C) 2002, 2010 by Eurecom
    author               : Michelle.Wetterwald@eurecom.fr
 **************************************************************************
  This file contains the code generated by the Esterel engine

  IT MUST NOT BE MODIFIED MANUALLY
 ***************************************************************************/
/********************
//OpenAir definitions
 ********************/
#include "LAYER2/MAC/extern.h"
#include "UTIL/MEM/mem_block.h"
//-----------------------------------------------------------------------------
//#include "rrc_rg_vars.h"
#include "rrc_rg.h"
//-----------------------------------------------------------------------------
/* "SAXORT STRL Compiler version 3.1.6n compiled on Fri_Oct_18_15:50:53_CEST_2002" */

/* automaton kernel code*/
//#include <stdlib.h>
//#include <stdio.h>
//#include <string.h>
#define SIZEOFINT 32
#define B_SET_VECTOR_MASK(i) ((unsigned int)1 << i)
#define B_RES_VECTOR_MASK(i) (~((unsigned int)1 << i))
#define BIT_SET(b_vector, bit_number) (b_vector)[(bit_number) / SIZEOFINT] |= B_SET_VECTOR_MASK((bit_number) % SIZEOFINT)
#define BIT_RESET(b_vector, bit_number) (b_vector)[(bit_number) / SIZEOFINT] &= ~B_SET_VECTOR_MASK((bit_number) % SIZEOFINT)

#define IS_ON(point) (_On[point / SIZEOFINT] & B_SET_VECTOR_MASK(point % SIZEOFINT))
#define IS_PAUSE_ON(point) (_Pause[point / SIZEOFINT] & B_SET_VECTOR_MASK(point % SIZEOFINT))

#define HALT_POINT_NUM 77
#define HALT_POINT_VECTOR_SIZE ((HALT_POINT_NUM-1)/(int)SIZEOFINT)+1
static unsigned int _On[HALT_POINT_VECTOR_SIZE];
static unsigned int _Pause[HALT_POINT_VECTOR_SIZE];

#define SIGNAL_NUM 63
#define SIGNAL_VECTOR_SIZE 2
#define SIGNAL_WITH_PRE_VECTOR_SIZE 1
#define GLOBALMAXPRELEVEL 1
static unsigned int _Sig[SIGNAL_VECTOR_SIZE];
#define EMIT(vector, signal) (vector)[signal / SIZEOFINT] |= B_SET_VECTOR_MASK(signal % SIZEOFINT)
#define CLEAR_SIGNAL(vector, signal) (vector)[signal / SIZEOFINT] &= B_RES_VECTOR_MASK(signal % SIZEOFINT)
#define IS_SIGNAL(vector, signal) ((vector)[signal / SIZEOFINT] & B_SET_VECTOR_MASK(signal % SIZEOFINT))

#define GUARD_NUM 20
#define GUARD_VECTOR_SIZE ((GUARD_NUM-1)/(int)SIZEOFINT)+1
static unsigned int _Guard[GUARD_VECTOR_SIZE];
#define IS_GUARD(guard) (_Guard[guard / SIZEOFINT] & B_SET_VECTOR_MASK(guard % SIZEOFINT))
#define SET_GUARD(guard) _Guard[guard / SIZEOFINT] |= B_SET_VECTOR_MASK(guard % SIZEOFINT)
#define RESET_GUARD(guard) _Guard[guard / SIZEOFINT] &= B_RES_VECTOR_MASK(guard % SIZEOFINT)

#ifndef _PREDEFINED_TYPES
#define _PREDEFINED_TYPES
typedef  int boolean;
typedef  int integer;
#ifndef STRLEN
#define STRLEN 81
#endif
typedef char *string;
#define _integer(x, y) (*x) = (y)
#define _boolean(x, y) (*x) = (y)
#define _float(x, y) (*x) = (y)
#define _double(x, y) (*x) = (y)
#define _string(x, y) strcpy((*x), (y))
#define _eq_integer(x, y) ((x) == (y))
#define _eq_boolean(x, y) ((x) == (y))
#define _eq_float(x, y) ((x) == (y))
#define _eq_double(x, y) ((x) == (y))
#define _eq_string(x, y) (!strcmp((x), (y)))
#define _ne_integer(x, y) ((x) != (y))
#define _ne_boolean(x, y) ((x) != (y))
#define _ne_float(x, y) ((x) != (y))
#define _ne_double(x, y) ((x) != (y))
#define _ne_string(x, y) (strcmp((x), (y)))
#define _cond_integer(x, y, z) ((x)?(y):(z))
#define _cond_boolean(x, y, z) ((x)?(y):(z))
#define _cond_float(x, y, z) ((x)?(y):(z))
#define _cond_double(x, y, z) ((x)?(y):(z))
#define _cond_string(x, y, z) ((x)?(y):(z))
#define _string_to_text(x) (x)
#define _text_to_string(x, y) (strcpy((*x), (y)))
#define _plus_(x, y) (x) + (y)
#define _minus_(x, y) (x) - (y)
#define _times_(x, y) (x) * (y)
#define _div_(x, y) (x) / (y)
#define _mod_(x, y) (x) % (y)
#define _not_(x) !(x)
#define _or_(x, y) (x) || (y)
#define _and_(x, y) (x) && (y)
#define _equal_(x, y) (x) == (y)
#define _diff_(x, y) (x) != (y)
#define _sup_(x, y) (x) > (y)
#define _supequal_(x, y) (x) >= (y)
#define _inf_(x, y) (x) < (y)
#define _infequal_(x, y) (x) <= (y)
#endif
#ifndef SUCCESS
extern integer SUCCESS;
#endif
#ifndef FAILURE
extern integer FAILURE;
#endif
#ifndef RRC_CONN_SETUP
extern integer RRC_CONN_SETUP;
#endif
#ifndef RRC_CONN_REJECT
extern integer RRC_CONN_REJECT;
#endif
#ifndef RRC_CONN_RELEASE
extern integer RRC_CONN_RELEASE;
#endif
#ifndef RB_SETUP
extern integer RB_SETUP;
#endif
#ifndef RB_RELEASE
extern integer RB_RELEASE;
#endif
#ifndef CELL_UPDATE_CONFIRM
extern integer CELL_UPDATE_CONFIRM;
#endif
#ifndef Conn_Received
extern integer Conn_Received;
#endif
#ifndef CELL_FACH_Connecting
extern integer CELL_FACH_Connecting;
#endif
#ifndef CELL_DCH_Connecting
extern integer CELL_DCH_Connecting;
#endif
#ifndef CELL_FACH_Connected
extern integer CELL_FACH_Connected;
#endif
#ifndef CELL_DCH_Connected
extern integer CELL_DCH_Connected;
#endif
#ifndef CELL_FACH_Releasing
extern integer CELL_FACH_Releasing;
#endif
#ifndef CELL_DCH_Releasing
extern integer CELL_DCH_Releasing;
#endif
#ifndef REL_COUNT
extern integer REL_COUNT;
#endif
#ifndef E_ADD_MT
extern integer E_ADD_MT;
#endif
#ifndef E_REL_MT
extern integer E_REL_MT;
#endif
#ifndef E_ADD_RB
extern integer E_ADD_RB;
#endif
#ifndef E_REL_RB
extern integer E_REL_RB;
#endif
#ifndef RB_FAIL_IDLE_MOBILE
extern integer RB_FAIL_IDLE_MOBILE;
#endif
#ifndef RB_FAIL_INVALID_CONFIG
extern integer RB_FAIL_INVALID_CONFIG;
#endif
#ifndef RB_FAIL_RLC_FAILURE
extern integer RB_FAIL_RLC_FAILURE;
#endif
#ifndef RB_FAIL_UE_SETUP_FAILURE
extern integer RB_FAIL_UE_SETUP_FAILURE;
#endif
static boolean Var__ThisIsTheEnd__171 ;
#define __Sig_Conn_Establish_complete_128 0
static integer Sig_UE_Id_129 ;
static integer Sig_Curr_State_130 ;
static integer Var_msg_132 ;
#define __Sig_sc_go_26_ConnEstab_REJECT_133 1
static integer Var_msgReq_134 ;
static  int Sig_Rel_repeat_135_Pre0 = 0;
static  int Sig_Rel_repeat_135_Pre1 = 0;
static integer Sig_Rel_repeat_135[2] ;
static integer Var_msg_137 ;
#define __Sig_sc_go_42_ConnRel_CFG_138 2
#define __Sig_sc_go_30_ConnRel_Send_136 3
static integer Var_msg_139 ;
#define __Sig_sc_cond12_144 4
#define __Sig_sc_cond14_147 5
#define __Sig_sc_cond13_148 6
#define __Sig_sc_cond16_151 7
#define __Sig_sc_cond15_152 8
#define __Sig_sc_go_34_RbEstab_Ack_142 9
#define __Sig_sc_go_41_RbEstab_fail_141 10
#define __Sig_sc_go_35_RbEstab_InitFailure_140 11
static integer Var_msg_154 ;
#define __Sig_sc_cond10_156 12
#define __Sig_sc_go_6_RelComp_CFG_159 13
#define __Sig_sc_go_14_RelComp_Proc_158 14
#define __Sig_sc_go_40_RbComp_L2_160 15
static integer Var_msg_161 ;
#define __Sig_sc_cond2_165 16
#define __Sig_sc_cond3_164 17
#define __Sig_sc_go_54_CellU_fail_162 18
#define __Sig_sc_cond8_168 19
#define __Sig_sc_go_48_RbFail_Phy_170 20
#define __Out_O_RB_failure_code_127 21
static integer Out_O_RB_failure_code_127 ;
#define __Out_O_Compute_Configuration_126 22
static integer Out_O_Compute_Configuration_126 ;
#define __Out_O_Action_125 23
static integer Out_O_Action_125 ;
#define __Out_O_CRLC_CONFIG_Req_124 24
#define __Out_O_CMAC_CONFIG_Req_123 25
#define __Out_O_CPHY_RL_RELEASE_Req_122 26
#define __Out_O_CPHY_RL_SETUP_Req_121 27
#define __Out_O_SEND_DCCH_AM_120 28
static integer Out_O_SEND_DCCH_AM_120 ;
#define __Out_O_SEND_DCCH_UM_119 29
static integer Out_O_SEND_DCCH_UM_119 ;
#define __Out_O_SEND_CCCH_118 30
static integer Out_O_SEND_CCCH_118 ;
#define __Out_O_NAS_CONN_LOSS_IND_117 31
static integer Out_O_NAS_CONN_LOSS_IND_117 ;
#define __Out_O_NAS_RB_Failure_116 32
static integer Out_O_NAS_RB_Failure_116 ;
#define __Out_O_NAS_RB_ESTAB_CNF_115 33
static integer Out_O_NAS_RB_ESTAB_CNF_115 ;
#define __Out_O_NAS_CONN_RELEASE_IND_114 34
static integer Out_O_NAS_CONN_RELEASE_IND_114 ;
#define __Out_O_NAS_CONN_ESTAB_IND_113 35
static integer Out_O_NAS_CONN_ESTAB_IND_113 ;
#define __In_I_Configuration_Failure_112 36
#define __In_I_Configuration_Indication_111 37
#define __In_I_Last_RB_110 38
#define __In_I_RB_List_109 39
static integer In_I_RB_List_109 ;
#define __In_I_Status_108 40
static integer In_I_Status_108 ;
#define __In_I_RLC_Failure_107 41
static integer In_I_RLC_Failure_107 ;
#define __In_I_RLC_Success_106 42
static integer In_I_RLC_Success_106 ;
#define __In_I_CRLC_STATUS_105 43
static integer In_I_CRLC_STATUS_105 ;
#define __In_I_CPHY_RL_MODIFY_Cnf_104 44
static integer In_I_CPHY_RL_MODIFY_Cnf_104 ;
#define __In_I_CPHY_RL_SETUP_Cnf_103 45
static integer In_I_CPHY_RL_SETUP_Cnf_103 ;
#define __In_I_CPHY_CONNECTION_LOSS_102 46
static integer In_I_CPHY_CONNECTION_LOSS_102 ;
#define __In_I_CPHY_OUT_OF_SYNCH_101 47
static integer In_I_CPHY_OUT_OF_SYNCH_101 ;
#define __In_I_CPHY_SYNCH_Failure_100 48
static integer In_I_CPHY_SYNCH_Failure_100 ;
#define __In_I_CPHY_SYNCH_IND_99 49
static integer In_I_CPHY_SYNCH_IND_99 ;
#define __In_I_NAS_RB_RELEASE_REQ_98 50
static integer In_I_NAS_RB_RELEASE_REQ_98 ;
#define __In_I_NAS_RB_ESTAB_REQ_97 51
static integer In_I_NAS_RB_ESTAB_REQ_97 ;
#define __In_I_NAS_CONN_RELEASE_REQ_96 52
static integer In_I_NAS_CONN_RELEASE_REQ_96 ;
#define __In_I_NAS_CONN_ESTAB_CNF_95 53
static integer In_I_NAS_CONN_ESTAB_CNF_95 ;
#define __In_I_CELL_UPDATE_94 54
static integer In_I_CELL_UPDATE_94 ;
#define __In_I_RB_REL_FAILURE_93 55
static integer In_I_RB_REL_FAILURE_93 ;
#define __In_I_RB_REL_COMPLETE_92 56
static integer In_I_RB_REL_COMPLETE_92 ;
#define __In_I_RB_SETUP_FAILURE_91 57
static integer In_I_RB_SETUP_FAILURE_91 ;
#define __In_I_RB_SETUP_COMPLETE_90 58
static integer In_I_RB_SETUP_COMPLETE_90 ;
#define __In_I_RRC_CONN_REL_COMPLETE_89 59
static integer In_I_RRC_CONN_REL_COMPLETE_89 ;
#define __In_I_RRC_CONNECTION_RELEASE_88 60
static integer In_I_RRC_CONNECTION_RELEASE_88 ;
#define __In_I_RRC_CONN_SETUP_COMPLETE_87 61
static integer In_I_RRC_CONN_SETUP_COMPLETE_87 ;
#define __In_I_RRC_CONNECTION_REQUEST_86 62
static integer In_I_RRC_CONNECTION_REQUEST_86 ;
#ifndef create_Mobile
extern void create_Mobile(integer);
#endif
#ifndef update_Mobile
extern void update_Mobile(integer, integer);
#endif
#ifndef delete_Mobile
extern void delete_Mobile(integer);
#endif
#ifndef release_DCH_Resources
extern void release_DCH_Resources(integer);
#endif
#ifndef restore_former_config
extern void restore_former_config(integer);
#endif
#ifndef encode_message
extern void encode_message(integer*, integer, integer);
#endif
#ifndef proc_RB_List
extern void proc_RB_List(integer*, integer, integer);
#endif
#ifndef rg_clear_transaction
extern void rg_clear_transaction(integer, integer);
#endif
#ifndef clear_rbsetup_variables
extern void clear_rbsetup_variables(integer);
#endif
#ifndef clear_rbrelease_variables
extern void clear_rbrelease_variables(integer);
#endif
#ifndef rg_update_UE_numrb
extern void rg_update_UE_numrb(integer, integer);
#endif
#ifndef Current_State
extern integer Current_State(integer);
#endif
#ifndef INTEGER_COMBINE
extern integer INTEGER_COMBINE(integer, integer);
#endif

extern void RRC_RG_O_O_RB_failure_code(integer);
extern void RRC_RG_O_O_Compute_Configuration(integer);
extern void RRC_RG_O_O_Action(integer);
extern void RRC_RG_O_O_CRLC_CONFIG_Req(void);
extern void RRC_RG_O_O_CMAC_CONFIG_Req(void);
extern void RRC_RG_O_O_CPHY_RL_RELEASE_Req(void);
extern void RRC_RG_O_O_CPHY_RL_SETUP_Req(void);
extern void RRC_RG_O_O_SEND_DCCH_AM(integer);
extern void RRC_RG_O_O_SEND_DCCH_UM(integer);
extern void RRC_RG_O_O_SEND_CCCH(integer);
extern void RRC_RG_O_O_NAS_CONN_LOSS_IND(integer);
extern void RRC_RG_O_O_NAS_RB_Failure(integer);
extern void RRC_RG_O_O_NAS_RB_ESTAB_CNF(integer);
extern void RRC_RG_O_O_NAS_CONN_RELEASE_IND(integer);
extern void RRC_RG_O_O_NAS_CONN_ESTAB_IND(integer);
void RRC_RG_I_I_Configuration_Failure(void) {
EMIT(_Sig, __In_I_Configuration_Failure_112);
 }
void RRC_RG_I_I_Configuration_Indication(void) {
EMIT(_Sig, __In_I_Configuration_Indication_111);
 }
void RRC_RG_I_I_Last_RB(void) {
EMIT(_Sig, __In_I_Last_RB_110);
 }
void RRC_RG_I_I_RB_List(integer value) {
EMIT(_Sig, __In_I_RB_List_109);
_integer(&In_I_RB_List_109, value);
 }
void RRC_RG_I_I_Status(integer value) {
EMIT(_Sig, __In_I_Status_108);
_integer(&In_I_Status_108, value);
 }
void RRC_RG_I_I_RLC_Failure(integer value) {
EMIT(_Sig, __In_I_RLC_Failure_107);
_integer(&In_I_RLC_Failure_107, value);
 }
void RRC_RG_I_I_RLC_Success(integer value) {
EMIT(_Sig, __In_I_RLC_Success_106);
_integer(&In_I_RLC_Success_106, value);
 }
void RRC_RG_I_I_CRLC_STATUS(integer value) {
EMIT(_Sig, __In_I_CRLC_STATUS_105);
_integer(&In_I_CRLC_STATUS_105, value);
 }
void RRC_RG_I_I_CPHY_RL_MODIFY_Cnf(integer value) {
EMIT(_Sig, __In_I_CPHY_RL_MODIFY_Cnf_104);
_integer(&In_I_CPHY_RL_MODIFY_Cnf_104, value);
 }
void RRC_RG_I_I_CPHY_RL_SETUP_Cnf(integer value) {
EMIT(_Sig, __In_I_CPHY_RL_SETUP_Cnf_103);
_integer(&In_I_CPHY_RL_SETUP_Cnf_103, value);
 }
void RRC_RG_I_I_CPHY_CONNECTION_LOSS(integer value) {
EMIT(_Sig, __In_I_CPHY_CONNECTION_LOSS_102);
_integer(&In_I_CPHY_CONNECTION_LOSS_102, value);
 }
void RRC_RG_I_I_CPHY_OUT_OF_SYNCH(integer value) {
EMIT(_Sig, __In_I_CPHY_OUT_OF_SYNCH_101);
_integer(&In_I_CPHY_OUT_OF_SYNCH_101, value);
 }
void RRC_RG_I_I_CPHY_SYNCH_Failure(integer value) {
EMIT(_Sig, __In_I_CPHY_SYNCH_Failure_100);
_integer(&In_I_CPHY_SYNCH_Failure_100, value);
 }
void RRC_RG_I_I_CPHY_SYNCH_IND(integer value) {
EMIT(_Sig, __In_I_CPHY_SYNCH_IND_99);
_integer(&In_I_CPHY_SYNCH_IND_99, value);
 }
void RRC_RG_I_I_NAS_RB_RELEASE_REQ(integer value) {
EMIT(_Sig, __In_I_NAS_RB_RELEASE_REQ_98);
_integer(&In_I_NAS_RB_RELEASE_REQ_98, value);
 }
void RRC_RG_I_I_NAS_RB_ESTAB_REQ(integer value) {
EMIT(_Sig, __In_I_NAS_RB_ESTAB_REQ_97);
_integer(&In_I_NAS_RB_ESTAB_REQ_97, value);
 }
void RRC_RG_I_I_NAS_CONN_RELEASE_REQ(integer value) {
EMIT(_Sig, __In_I_NAS_CONN_RELEASE_REQ_96);
_integer(&In_I_NAS_CONN_RELEASE_REQ_96, value);
 }
void RRC_RG_I_I_NAS_CONN_ESTAB_CNF(integer value) {
EMIT(_Sig, __In_I_NAS_CONN_ESTAB_CNF_95);
_integer(&In_I_NAS_CONN_ESTAB_CNF_95, value);
 }
void RRC_RG_I_I_CELL_UPDATE(integer value) {
EMIT(_Sig, __In_I_CELL_UPDATE_94);
_integer(&In_I_CELL_UPDATE_94, value);
 }
void RRC_RG_I_I_RB_REL_FAILURE(integer value) {
EMIT(_Sig, __In_I_RB_REL_FAILURE_93);
_integer(&In_I_RB_REL_FAILURE_93, value);
 }
void RRC_RG_I_I_RB_REL_COMPLETE(integer value) {
EMIT(_Sig, __In_I_RB_REL_COMPLETE_92);
_integer(&In_I_RB_REL_COMPLETE_92, value);
 }
void RRC_RG_I_I_RB_SETUP_FAILURE(integer value) {
EMIT(_Sig, __In_I_RB_SETUP_FAILURE_91);
_integer(&In_I_RB_SETUP_FAILURE_91, value);
 }
void RRC_RG_I_I_RB_SETUP_COMPLETE(integer value) {
EMIT(_Sig, __In_I_RB_SETUP_COMPLETE_90);
_integer(&In_I_RB_SETUP_COMPLETE_90, value);
 }
void RRC_RG_I_I_RRC_CONN_REL_COMPLETE(integer value) {
EMIT(_Sig, __In_I_RRC_CONN_REL_COMPLETE_89);
_integer(&In_I_RRC_CONN_REL_COMPLETE_89, value);
 }
void RRC_RG_I_I_RRC_CONNECTION_RELEASE(integer value) {
EMIT(_Sig, __In_I_RRC_CONNECTION_RELEASE_88);
_integer(&In_I_RRC_CONNECTION_RELEASE_88, value);
 }
void RRC_RG_I_I_RRC_CONN_SETUP_COMPLETE(integer value) {
EMIT(_Sig, __In_I_RRC_CONN_SETUP_COMPLETE_87);
_integer(&In_I_RRC_CONN_SETUP_COMPLETE_87, value);
 }
void RRC_RG_I_I_RRC_CONNECTION_REQUEST(integer value) {
EMIT(_Sig, __In_I_RRC_CONNECTION_REQUEST_86);
_integer(&In_I_RRC_CONNECTION_REQUEST_86, value);
 }

static void Point_0(void) {
/*#0 */
    _boolean(&Var__ThisIsTheEnd__171, 1);
    _Pause[0] |= 0xfb9c; /* PauseOn: #2 #3 #4 #7 #8 #9 #11 #12 #13 #14 #15 */
}

static void Point_1(void) {
/*#1 AutoPauseOn */
    if (IS_SIGNAL(_Sig, __In_I_CPHY_SYNCH_IND_99)) {
        EMIT(_Sig, __Sig_Conn_Establish_complete_128);
        _On[2] |= 0x100; /* On: #72 */
        _On[0] &= ~0x2; /* Off: #1 */
    }
}

static void Point_2(void) {
/*#2 AutoPauseOn */
    if (IS_SIGNAL(_Sig, __In_I_NAS_CONN_ESTAB_CNF_95)) {
        if (!(IS_GUARD(0))) 
            _integer(&Sig_UE_Id_129, In_I_NAS_CONN_ESTAB_CNF_95);
        else
            _integer(&Sig_UE_Id_129, INTEGER_COMBINE(Sig_UE_Id_129, In_I_NAS_CONN_ESTAB_CNF_95));
        SET_GUARD(0); 
        _On[2] |= 0x4; /* On: #66 */
        _On[0] &= ~0x4; /* Off: #2 */
    }
}

static void Point_3(void) {
/*#3 AutoPauseOn */
    if (IS_SIGNAL(_Sig, __In_I_RRC_CONNECTION_REQUEST_86)) {
        if (!(IS_GUARD(0))) 
            _integer(&Sig_UE_Id_129, In_I_RRC_CONNECTION_REQUEST_86);
        else
            _integer(&Sig_UE_Id_129, INTEGER_COMBINE(Sig_UE_Id_129, In_I_RRC_CONNECTION_REQUEST_86));
        SET_GUARD(0); 
        _On[1] |= 0x40000000; /* On: #62 */
        _On[0] &= ~0x8; /* Off: #3 */
    }
}

static void Point_4(void) {
/*#4 AutoPauseOn */
    if (IS_SIGNAL(_Sig, __In_I_RRC_CONN_SETUP_COMPLETE_87)) {
        if (!(IS_GUARD(0))) 
            _integer(&Sig_UE_Id_129, In_I_RRC_CONN_SETUP_COMPLETE_87);
        else
            _integer(&Sig_UE_Id_129, INTEGER_COMBINE(Sig_UE_Id_129, In_I_RRC_CONN_SETUP_COMPLETE_87));
        SET_GUARD(0); 
        _On[1] |= 0x4000000; /* On: #58 */
        _On[0] &= ~0x10; /* Off: #4 */
    }
}

static void Point_5(void) {
/*#5 AutoPauseOn */
    if (IS_SIGNAL(_Sig, __In_I_Configuration_Indication_111)) {
        EMIT(_Sig, __Sig_sc_go_30_ConnRel_Send_136);
        _On[1] |= 0x2000000; /* On: #57 */
        _On[0] &= ~0x20; /* Off: #5 */
    } else {
        if (IS_SIGNAL(_Sig, __In_I_Configuration_Failure_112)) {
            _On[1] |= 0x2000000; /* On: #57 */
            _On[0] &= ~0x20; /* Off: #5 */
        }
    }
}

static void Point_6(void) {
/*#6 */
    if ((Sig_Rel_repeat_135[Sig_Rel_repeat_135_Pre1] > 1)) {
        Sig_Rel_repeat_135_Pre0 = Sig_Rel_repeat_135_Pre1 ^ 1;
        _integer(&Sig_Rel_repeat_135[Sig_Rel_repeat_135_Pre0], (Sig_Rel_repeat_135[Sig_Rel_repeat_135_Pre1] - 1));
        EMIT(_Sig, __Sig_sc_go_30_ConnRel_Send_136);
        _On[1] |= 0x2000000; /* On: #57 */
    } else {
        _On[1] |= 0x2000000; /* On: #57 */
    }
}

static void Point_7(void) {
/*#7 AutoPauseOn */
    if (IS_SIGNAL(_Sig, __In_I_NAS_CONN_RELEASE_REQ_96)) {
        if (!(IS_GUARD(0))) 
            _integer(&Sig_UE_Id_129, In_I_NAS_CONN_RELEASE_REQ_96);
        else
            _integer(&Sig_UE_Id_129, INTEGER_COMBINE(Sig_UE_Id_129, In_I_NAS_CONN_RELEASE_REQ_96));
        SET_GUARD(0); 
        Sig_Rel_repeat_135_Pre0 = Sig_Rel_repeat_135_Pre1 ^ 1;
        _integer(&Sig_Rel_repeat_135[Sig_Rel_repeat_135_Pre0], REL_COUNT);
        _On[1] |= 0x1000000; /* On: #56 */
        _On[0] &= ~0x80; /* Off: #7 */
    }
}

static void Point_8(void) {
/*#8 AutoPauseOn */
    if (IS_SIGNAL(_Sig, __In_I_NAS_RB_ESTAB_REQ_97)) {
        if (!(IS_GUARD(0))) 
            _integer(&Sig_UE_Id_129, In_I_NAS_RB_ESTAB_REQ_97);
        else
            _integer(&Sig_UE_Id_129, INTEGER_COMBINE(Sig_UE_Id_129, In_I_NAS_RB_ESTAB_REQ_97));
        SET_GUARD(0); 
        _On[1] |= 0x400; /* On: #42 */
        _On[0] &= ~0x100; /* Off: #8 */
    }
}

static void Point_9(void) {
/*#9 AutoPauseOn */
    if (IS_SIGNAL(_Sig, __In_I_NAS_RB_RELEASE_REQ_98)) {
        if (!(IS_GUARD(0))) 
            _integer(&Sig_UE_Id_129, In_I_NAS_RB_RELEASE_REQ_98);
        else
            _integer(&Sig_UE_Id_129, INTEGER_COMBINE(Sig_UE_Id_129, In_I_NAS_RB_RELEASE_REQ_98));
        SET_GUARD(0); 
        _On[1] |= 0x20; /* On: #37 */
        _On[0] &= ~0x200; /* Off: #9 */
    }
}

static void Point_10(void) {
/*#10 AutoPauseOn */
    if ((IS_SIGNAL(_Sig, __In_I_Configuration_Indication_111) || IS_SIGNAL(_Sig, __In_I_Configuration_Failure_112))) {
        EMIT(_Sig, __Sig_sc_go_14_RelComp_Proc_158);
        _On[1] |= 0x8; /* On: #35 */
        _On[0] &= ~0x400; /* Off: #10 */
    }
}

static void Point_11(void) {
/*#11 AutoPauseOn */
    if (IS_SIGNAL(_Sig, __In_I_RRC_CONNECTION_RELEASE_88)) {
        if (!(IS_GUARD(0))) 
            _integer(&Sig_UE_Id_129, In_I_RRC_CONNECTION_RELEASE_88);
        else
            _integer(&Sig_UE_Id_129, INTEGER_COMBINE(Sig_UE_Id_129, In_I_RRC_CONNECTION_RELEASE_88));
        SET_GUARD(0); 
        _On[1] |= 0x1; /* On: #32 */
        _On[0] &= ~0x800; /* Off: #11 */
    } else {
        if (IS_SIGNAL(_Sig, __In_I_CPHY_CONNECTION_LOSS_102)) {
            if (!(IS_GUARD(0))) 
                _integer(&Sig_UE_Id_129, In_I_CPHY_CONNECTION_LOSS_102);
            else
                _integer(&Sig_UE_Id_129, INTEGER_COMBINE(Sig_UE_Id_129, In_I_CPHY_CONNECTION_LOSS_102));
            SET_GUARD(0); 
            EMIT(_Sig, __Out_O_NAS_CONN_LOSS_IND_117);
            _On[0] |= 0x80000000; /* On: #31 */
            _On[0] &= ~0x800; /* Off: #11 */
        } else {
            if (IS_SIGNAL(_Sig, __In_I_CPHY_OUT_OF_SYNCH_101)) {
                if (!(IS_GUARD(0))) 
                    _integer(&Sig_UE_Id_129, In_I_CPHY_OUT_OF_SYNCH_101);
                else
                    _integer(&Sig_UE_Id_129, INTEGER_COMBINE(Sig_UE_Id_129, In_I_CPHY_OUT_OF_SYNCH_101));
                SET_GUARD(0); 
                _On[0] |= 0x40000000; /* On: #30 */
                _On[0] &= ~0x800; /* Off: #11 */
            } else {
                if (IS_SIGNAL(_Sig, __In_I_RRC_CONN_REL_COMPLETE_89)) {
                    if (!(IS_GUARD(0))) 
                        _integer(&Sig_UE_Id_129, In_I_RRC_CONN_REL_COMPLETE_89);
                    else
                        _integer(&Sig_UE_Id_129, INTEGER_COMBINE(Sig_UE_Id_129, In_I_RRC_CONN_REL_COMPLETE_89));
                    SET_GUARD(0); 
                    _On[0] |= 0x20000000; /* On: #29 */
                    _On[0] &= ~0x800; /* Off: #11 */
                }
            }
        }
    }
}

static void Point_12(void) {
/*#12 AutoPauseOn */
    if (IS_SIGNAL(_Sig, __In_I_RB_SETUP_COMPLETE_90)) {
        if (!(IS_GUARD(0))) 
            _integer(&Sig_UE_Id_129, In_I_RB_SETUP_COMPLETE_90);
        else
            _integer(&Sig_UE_Id_129, INTEGER_COMBINE(Sig_UE_Id_129, In_I_RB_SETUP_COMPLETE_90));
        SET_GUARD(0); 
        _On[0] |= 0x4000000; /* On: #26 */
        _On[0] &= ~0x1000; /* Off: #12 */
    }
}

static void Point_13(void) {
/*#13 AutoPauseOn */
    if (IS_SIGNAL(_Sig, __In_I_CRLC_STATUS_105)) {
        if (!(IS_GUARD(0))) 
            _integer(&Sig_UE_Id_129, In_I_CRLC_STATUS_105);
        else
            _integer(&Sig_UE_Id_129, INTEGER_COMBINE(Sig_UE_Id_129, In_I_CRLC_STATUS_105));
        SET_GUARD(0); 
        _On[0] |= 0x2000000; /* On: #25 */
        _On[0] &= ~0x2000; /* Off: #13 */
    } else {
        if (IS_SIGNAL(_Sig, __In_I_CELL_UPDATE_94)) {
            if (!(IS_GUARD(0))) 
                _integer(&Sig_UE_Id_129, In_I_CELL_UPDATE_94);
            else
                _integer(&Sig_UE_Id_129, INTEGER_COMBINE(Sig_UE_Id_129, In_I_CELL_UPDATE_94));
            SET_GUARD(0); 
            _On[0] |= 0x2000000; /* On: #25 */
            _On[0] &= ~0x2000; /* Off: #13 */
        }
    }
}

static void Point_14(void) {
/*#14 AutoPauseOn */
    if (IS_SIGNAL(_Sig, __In_I_RB_REL_COMPLETE_92)) {
        if (!(IS_GUARD(0))) 
            _integer(&Sig_UE_Id_129, In_I_RB_REL_COMPLETE_92);
        else
            _integer(&Sig_UE_Id_129, INTEGER_COMBINE(Sig_UE_Id_129, In_I_RB_REL_COMPLETE_92));
        SET_GUARD(0); 
        _On[0] |= 0x20000; /* On: #17 */
        _On[0] &= ~0x4000; /* Off: #14 */
    }
}

static void Point_15(void) {
/*#15 AutoPauseOn */
    if (IS_SIGNAL(_Sig, __In_I_RB_SETUP_FAILURE_91)) {
        SET_GUARD(0); 
        if (!(IS_GUARD(0))) 
            _integer(&Sig_UE_Id_129, In_I_RB_SETUP_FAILURE_91);
        else
            _integer(&Sig_UE_Id_129, INTEGER_COMBINE(Sig_UE_Id_129, In_I_RB_SETUP_FAILURE_91));
        SET_GUARD(0); 
        _On[0] &= ~0x8000; /* Off: #15 */
        if ((_eq_integer(Current_State(Sig_UE_Id_129), CELL_FACH_Connected) || _eq_integer(Current_State(Sig_UE_Id_129), CELL_DCH_Connected))) {
            EMIT(_Sig, __Sig_sc_go_48_RbFail_Phy_170);
        }
    } else {
        if (IS_SIGNAL(_Sig, __In_I_RB_REL_FAILURE_93)) {
            SET_GUARD(0); 
            if (!(IS_GUARD(0))) 
                _integer(&Sig_UE_Id_129, In_I_RB_REL_FAILURE_93);
            else
                _integer(&Sig_UE_Id_129, INTEGER_COMBINE(Sig_UE_Id_129, In_I_RB_REL_FAILURE_93));
            SET_GUARD(0); 
            _On[0] &= ~0x8000; /* Off: #15 */
            if (_eq_integer(Current_State(Sig_UE_Id_129), CELL_DCH_Connected)) {
                EMIT(_Sig, __Sig_sc_go_48_RbFail_Phy_170);
            }
        }
    }
    if (IS_GUARD(0)) {
        if (IS_SIGNAL(_Sig, __Sig_sc_go_48_RbFail_Phy_170)) {
            restore_former_config(Sig_UE_Id_129);
            EMIT(_Sig, __Out_O_RB_failure_code_127);
            if (!(IS_GUARD(7))) 
                _integer(&Out_O_RB_failure_code_127, RB_FAIL_UE_SETUP_FAILURE);
            else
                _integer(&Out_O_RB_failure_code_127, INTEGER_COMBINE(Out_O_RB_failure_code_127, RB_FAIL_UE_SETUP_FAILURE));
            SET_GUARD(7); 
            _On[0] |= 0x10000; _On[1] |= 0x1000; /* On: #16 #44 */
        } else {
            _Pause[0] |= 0x8000; /* PauseOn: #15 */
        }
    }
}

static void Point_16(void) {
/*#16 */
    EMIT(_Sig, __Out_O_NAS_RB_Failure_116);
    if (!(IS_GUARD(18))) 
        _integer(&Out_O_NAS_RB_Failure_116, Sig_UE_Id_129);
    else
        _integer(&Out_O_NAS_RB_Failure_116, INTEGER_COMBINE(Out_O_NAS_RB_Failure_116, Sig_UE_Id_129));
    SET_GUARD(18); 
    _On[1] |= 0x400000; /* On: #54 */
    _Pause[0] |= 0x8000; /* PauseOn: #15 */
}

static void Point_17(void) {
/*#17 */
    if (_eq_integer(Current_State(Sig_UE_Id_129), CELL_DCH_Connected)) {
        if (IS_SIGNAL(_Sig, __In_I_Last_RB_110)) {
            update_Mobile(Sig_UE_Id_129, CELL_FACH_Connected);
            _On[0] |= 0x40000; /* On: #18 */
        } else {
            _On[0] |= 0x40000; /* On: #18 */
        }
        rg_update_UE_numrb(Sig_UE_Id_129, E_REL_RB);
        EMIT(_Sig, __Out_O_CRLC_CONFIG_Req_124);
        if (!(IS_GUARD(10))) { RRC_RG_O_O_CRLC_CONFIG_Req(); SET_GUARD(10); }
    } else {
        _On[0] |= 0x200000; /* On: #21 */
    }
}

static void Point_18(void) {
/*#18 */
    EMIT(_Sig, __Out_O_CMAC_CONFIG_Req_123);
    if (!(IS_GUARD(11))) { RRC_RG_O_O_CMAC_CONFIG_Req(); SET_GUARD(11); }
    EMIT(_Sig, __Out_O_CPHY_RL_RELEASE_Req_122);
    if (!(IS_GUARD(12))) { RRC_RG_O_O_CPHY_RL_RELEASE_Req(); SET_GUARD(12); }
    _Pause[0] |= 0x180000; /* PauseOn: #19 #20 */
}

static void Point_19(void) {
/*#19 AutoPauseOn */
    if (IS_SIGNAL(_Sig, __In_I_CPHY_RL_MODIFY_Cnf_104)) {
        if (_eq_integer(In_I_CPHY_RL_MODIFY_Cnf_104, Sig_UE_Id_129)) {
            EMIT(_Sig, __Sig_sc_cond8_168);
            _On[0] &= ~0x80000; /* Off: #19 */
        }
    }
}

static void Point_20(void) {
/*#20 AutoPauseOn */
    if (IS_SIGNAL(_Sig, __Sig_sc_cond8_168)) {
        clear_rbrelease_variables(Sig_UE_Id_129);
        _On[0] |= 0x200000; /* On: #21 */
        _On[0] &= ~0x100000; /* Off: #20 */
        _Pause[0] &= ~0x80000; _On[0] &= ~0x80000; /* PauseOff: #19 */
    }
}

static void Point_21(void) {
/*#21 */
    _Pause[0] |= 0x4000; /* PauseOn: #14 */
}

static void Point_22(void) {
/*#22 AutoPauseOn */
    if (IS_SIGNAL(_Sig, __In_I_CPHY_SYNCH_IND_99)) {
        if (_eq_integer(In_I_CPHY_SYNCH_IND_99, Sig_UE_Id_129)) {
            EMIT(_Sig, __Sig_sc_cond2_165);
            _On[0] &= ~0x400000; /* Off: #22 */
        } else {
            SET_GUARD(1); 
        }
    } else {
        SET_GUARD(1); 
    }
    if (IS_GUARD(1)) {
        if (IS_SIGNAL(_Sig, __In_I_CPHY_SYNCH_Failure_100)) {
            if (_eq_integer(In_I_CPHY_SYNCH_Failure_100, Sig_UE_Id_129)) {
                EMIT(_Sig, __Sig_sc_cond3_164);
                _On[0] &= ~0x400000; /* Off: #22 */
            }
        }
    }
}

static void Point_23(void) {
/*#23 AutoPauseOn */
    if (IS_SIGNAL(_Sig, __Sig_sc_cond2_165)) {
        SET_GUARD(2); 
        _On[0] &= ~0x800000; /* Off: #23 */
    } else {
        if (IS_SIGNAL(_Sig, __Sig_sc_cond3_164)) {
            SET_GUARD(2); 
            EMIT(_Sig, __Sig_sc_go_54_CellU_fail_162);
            _On[0] &= ~0x800000; /* Off: #23 */
        }
    }
    if (IS_GUARD(2)) {
        _Pause[0] &= ~0x400000; _On[0] &= ~0x400000; /* PauseOff: #22 */
        if (IS_SIGNAL(_Sig, __Sig_sc_go_54_CellU_fail_162)) {
            encode_message(&Var_msg_161, Sig_UE_Id_129, RRC_CONN_RELEASE);
            EMIT(_Sig, __Out_O_SEND_CCCH_118);
            if (!(IS_GUARD(16))) 
                _integer(&Out_O_SEND_CCCH_118, Var_msg_161);
            else
                _integer(&Out_O_SEND_CCCH_118, INTEGER_COMBINE(Out_O_SEND_CCCH_118, Var_msg_161));
            SET_GUARD(16); 
            EMIT(_Sig, __Out_O_NAS_CONN_LOSS_IND_117);
            if (!(IS_GUARD(17))) 
                _integer(&Out_O_NAS_CONN_LOSS_IND_117, Sig_UE_Id_129);
            else
                _integer(&Out_O_NAS_CONN_LOSS_IND_117, INTEGER_COMBINE(Out_O_NAS_CONN_LOSS_IND_117, Sig_UE_Id_129));
            SET_GUARD(17); 
            _On[0] |= 0x1000000; _On[1] |= 0x4; _On[2] |= 0x400; /* On: #24 #34 #74 */
        } else {
            _Pause[0] |= 0x2000; /* PauseOn: #13 */
        }
    }
}

static void Point_24(void) {
/*#24 */
    if (_eq_integer(Current_State(Sig_UE_Id_129), CELL_DCH_Connected)) {
        update_Mobile(Sig_UE_Id_129, CELL_DCH_Releasing);
        _Pause[0] |= 0x2000; /* PauseOn: #13 */
    } else {
        update_Mobile(Sig_UE_Id_129, CELL_FACH_Releasing);
        _Pause[0] |= 0x2000; /* PauseOn: #13 */
    }
}

static void Point_25(void) {
/*#25 */
    if ((_eq_integer(Current_State(Sig_UE_Id_129), CELL_FACH_Connected) || _eq_integer(Current_State(Sig_UE_Id_129), CELL_DCH_Connected))) {
        encode_message(&Var_msg_161, Sig_UE_Id_129, CELL_UPDATE_CONFIRM);
        EMIT(_Sig, __Out_O_SEND_CCCH_118);
        if (!(IS_GUARD(16))) 
            _integer(&Out_O_SEND_CCCH_118, Var_msg_161);
        else
            _integer(&Out_O_SEND_CCCH_118, INTEGER_COMBINE(Out_O_SEND_CCCH_118, Var_msg_161));
        SET_GUARD(16); 
        _On[2] |= 0x400; /* On: #74 */
        _Pause[0] |= 0xc00000; /* PauseOn: #22 #23 */
    } else {
        _Pause[0] |= 0x2000; /* PauseOn: #13 */
    }
}

static void Point_26(void) {
/*#26 */
    if (_eq_integer(Current_State(Sig_UE_Id_129), CELL_DCH_Connected)) {
        EMIT(_Sig, __Sig_sc_go_40_RbComp_L2_160);
    } else {
        if (_eq_integer(Current_State(Sig_UE_Id_129), CELL_FACH_Connected)) {
            update_Mobile(Sig_UE_Id_129, CELL_DCH_Connected);
            EMIT(_Sig, __Sig_sc_go_40_RbComp_L2_160);
        }
    }
    if (IS_SIGNAL(_Sig, __Sig_sc_go_40_RbComp_L2_160)) {
        _On[0] |= 0x8000000; /* On: #27 */
    } else {
        _Pause[0] |= 0x1000; /* PauseOn: #12 */
    }
}

static void Point_27(void) {
/*#27 */
    EMIT(_Sig, __Out_O_CRLC_CONFIG_Req_124);
    if (!(IS_GUARD(10))) { RRC_RG_O_O_CRLC_CONFIG_Req(); SET_GUARD(10); }
    EMIT(_Sig, __Out_O_CMAC_CONFIG_Req_123);
    if (!(IS_GUARD(11))) { RRC_RG_O_O_CMAC_CONFIG_Req(); SET_GUARD(11); }
    EMIT(_Sig, __Out_O_NAS_RB_ESTAB_CNF_115);
    _integer(&Out_O_NAS_RB_ESTAB_CNF_115, Sig_UE_Id_129);
    RRC_RG_O_O_NAS_RB_ESTAB_CNF(Out_O_NAS_RB_ESTAB_CNF_115); 
    _On[0] |= 0x10000000; /* On: #28 */
}

static void Point_28(void) {
/*#28 */
    clear_rbsetup_variables(Sig_UE_Id_129);
    _Pause[0] |= 0x1000; /* PauseOn: #12 */
}

static void Point_29(void) {
/*#29 */
    if ((_eq_integer(Current_State(Sig_UE_Id_129), CELL_DCH_Releasing) || _eq_integer(Current_State(Sig_UE_Id_129), CELL_FACH_Releasing))) {
        EMIT(_Sig, __Sig_sc_go_14_RelComp_Proc_158);
        _On[1] |= 0x2; /* On: #33 */
    } else {
        _On[1] |= 0x2; /* On: #33 */
    }
}

static void Point_30(void) {
/*#30 */
    if (_eq_integer(Current_State(Sig_UE_Id_129), CELL_DCH_Releasing)) {
        EMIT(_Sig, __Sig_sc_go_6_RelComp_CFG_159);
        _On[1] |= 0x2; /* On: #33 */
    } else {
        _On[1] |= 0x2; /* On: #33 */
    }
}

static void Point_31(void) {
/*#31 */
    if (!(IS_GUARD(17))) 
        _integer(&Out_O_NAS_CONN_LOSS_IND_117, Sig_UE_Id_129);
    else
        _integer(&Out_O_NAS_CONN_LOSS_IND_117, INTEGER_COMBINE(Out_O_NAS_CONN_LOSS_IND_117, Sig_UE_Id_129));
    SET_GUARD(17); 
    EMIT(_Sig, __Sig_sc_go_6_RelComp_CFG_159);
    _On[1] |= 0x6; /* On: #33 #34 */
}

static void Point_32(void) {
/*#32 */
    if ((_eq_integer(Current_State(Sig_UE_Id_129), CELL_DCH_Connected) || _eq_integer(Current_State(Sig_UE_Id_129), CELL_FACH_Connected))) {
        EMIT(_Sig, __Out_O_NAS_CONN_RELEASE_IND_114);
        if (!(IS_GUARD(19))) 
            _integer(&Out_O_NAS_CONN_RELEASE_IND_114, Sig_UE_Id_129);
        else
            _integer(&Out_O_NAS_CONN_RELEASE_IND_114, INTEGER_COMBINE(Out_O_NAS_CONN_RELEASE_IND_114, Sig_UE_Id_129));
        SET_GUARD(19); 
        EMIT(_Sig, __Sig_sc_go_6_RelComp_CFG_159);
        _On[1] |= 0x2; _On[2] |= 0x80; /* On: #33 #71 */
    } else {
        _On[1] |= 0x2; /* On: #33 */
    }
}

static void Point_33(void) {
/*#33 */
    if (IS_SIGNAL(_Sig, __Sig_sc_go_6_RelComp_CFG_159)) {
        EMIT(_Sig, __Out_O_Action_125);
        if (!(IS_GUARD(9))) 
            _integer(&Out_O_Action_125, E_REL_MT);
        else
            _integer(&Out_O_Action_125, INTEGER_COMBINE(Out_O_Action_125, E_REL_MT));
        SET_GUARD(9); 
        EMIT(_Sig, __Out_O_Compute_Configuration_126);
        if (!(IS_GUARD(8))) 
            _integer(&Out_O_Compute_Configuration_126, Sig_UE_Id_129);
        else
            _integer(&Out_O_Compute_Configuration_126, INTEGER_COMBINE(Out_O_Compute_Configuration_126, Sig_UE_Id_129));
        SET_GUARD(8); 
        _On[2] |= 0x1000; /* On: #76 */
        _Pause[0] |= 0x400; /* PauseOn: #10 */
    } else {
        _On[1] |= 0x8; /* On: #35 */
    }
}

static void Point_34(void) {
/*#34 */
    RRC_RG_O_O_NAS_CONN_LOSS_IND(Out_O_NAS_CONN_LOSS_IND_117); 
}

static void Point_35(void) {
/*#35 */
    if (IS_SIGNAL(_Sig, __Sig_sc_go_14_RelComp_Proc_158)) {
        release_DCH_Resources(Sig_UE_Id_129);
        delete_Mobile(Sig_UE_Id_129);
        _On[1] |= 0x10; /* On: #36 */
    } else {
        _On[1] |= 0x10; /* On: #36 */
    }
}

static void Point_36(void) {
/*#36 */
    _Pause[0] |= 0x800; /* PauseOn: #11 */
}

static void Point_37(void) {
/*#37 */
    if (_eq_integer(Current_State(Sig_UE_Id_129), CELL_DCH_Connected)) {
        proc_RB_List(&Var_msg_154, In_I_RB_List_109, Sig_UE_Id_129);
        EMIT(_Sig, __Out_O_Action_125);
        if (!(IS_GUARD(9))) 
            _integer(&Out_O_Action_125, E_REL_RB);
        else
            _integer(&Out_O_Action_125, INTEGER_COMBINE(Out_O_Action_125, E_REL_RB));
        SET_GUARD(9); 
        EMIT(_Sig, __Out_O_Compute_Configuration_126);
        if (!(IS_GUARD(8))) 
            _integer(&Out_O_Compute_Configuration_126, Sig_UE_Id_129);
        else
            _integer(&Out_O_Compute_Configuration_126, INTEGER_COMBINE(Out_O_Compute_Configuration_126, Sig_UE_Id_129));
        SET_GUARD(8); 
        _On[2] |= 0x1000; /* On: #76 */
        _Pause[1] |= 0x40; /* PauseOn: #38 */
    } else {
        _On[1] |= 0x200; /* On: #41 */
    }
}

static void Point_38(void) {
/*#38 AutoPauseOn */
    if (IS_SIGNAL(_Sig, __In_I_Configuration_Indication_111)) {
        encode_message(&Var_msg_154, Sig_UE_Id_129, RB_RELEASE);
        EMIT(_Sig, __Out_O_SEND_DCCH_AM_120);
        if (!(IS_GUARD(14))) 
            _integer(&Out_O_SEND_DCCH_AM_120, Var_msg_154);
        else
            _integer(&Out_O_SEND_DCCH_AM_120, INTEGER_COMBINE(Out_O_SEND_DCCH_AM_120, Var_msg_154));
        SET_GUARD(14); 
        _On[1] |= 0x10000; /* On: #48 */
        _On[1] &= ~0x40; /* Off: #38 */
        _Pause[1] |= 0x180; /* PauseOn: #39 #40 */
    } else {
        if (IS_SIGNAL(_Sig, __In_I_Configuration_Failure_112)) {
            _On[1] |= 0x200; /* On: #41 */
            _On[1] &= ~0x40; /* Off: #38 */
        }
    }
}

static void Point_39(void) {
/*#39 AutoPauseOn */
    if (IS_SIGNAL(_Sig, __In_I_RLC_Success_106)) {
        if (_eq_integer(In_I_RLC_Success_106, Sig_UE_Id_129)) {
            EMIT(_Sig, __Sig_sc_cond10_156);
            _On[1] &= ~0x80; /* Off: #39 */
        }
    }
}

static void Point_40(void) {
/*#40 AutoPauseOn */
    if (IS_SIGNAL(_Sig, __Sig_sc_cond10_156)) {
        _On[1] |= 0x200; /* On: #41 */
        _On[1] &= ~0x100; /* Off: #40 */
        _Pause[1] &= ~0x80; _On[1] &= ~0x80; /* PauseOff: #39 */
    }
}

static void Point_41(void) {
/*#41 */
    _Pause[0] |= 0x200; /* PauseOn: #9 */
}

static void Point_42(void) {
/*#42 */
    if ((_eq_integer(Current_State(Sig_UE_Id_129), CELL_FACH_Connected) || _eq_integer(Current_State(Sig_UE_Id_129), CELL_DCH_Connected))) {
        proc_RB_List(&Var_msg_139, In_I_RB_List_109, Sig_UE_Id_129);
        EMIT(_Sig, __Out_O_Action_125);
        if (!(IS_GUARD(9))) 
            _integer(&Out_O_Action_125, E_ADD_RB);
        else
            _integer(&Out_O_Action_125, INTEGER_COMBINE(Out_O_Action_125, E_ADD_RB));
        SET_GUARD(9); 
        EMIT(_Sig, __Out_O_Compute_Configuration_126);
        if (!(IS_GUARD(8))) 
            _integer(&Out_O_Compute_Configuration_126, Sig_UE_Id_129);
        else
            _integer(&Out_O_Compute_Configuration_126, INTEGER_COMBINE(Out_O_Compute_Configuration_126, Sig_UE_Id_129));
        SET_GUARD(8); 
        _On[2] |= 0x1000; /* On: #76 */
        _Pause[1] |= 0x800; /* PauseOn: #43 */
    } else {
        EMIT(_Sig, __Out_O_RB_failure_code_127);
        if (!(IS_GUARD(7))) 
            _integer(&Out_O_RB_failure_code_127, RB_FAIL_IDLE_MOBILE);
        else
            _integer(&Out_O_RB_failure_code_127, INTEGER_COMBINE(Out_O_RB_failure_code_127, RB_FAIL_IDLE_MOBILE));
        SET_GUARD(7); 
        EMIT(_Sig, __Sig_sc_go_35_RbEstab_InitFailure_140);
        _On[1] |= 0x201000; /* On: #44 #53 */
    }
}

static void Point_43(void) {
/*#43 AutoPauseOn */
    if (IS_SIGNAL(_Sig, __In_I_Configuration_Indication_111)) {
        rg_update_UE_numrb(Sig_UE_Id_129, E_ADD_RB);
        EMIT(_Sig, __Out_O_CPHY_RL_SETUP_Req_121);
        if (!(IS_GUARD(13))) { RRC_RG_O_O_CPHY_RL_SETUP_Req(); SET_GUARD(13); }
        _On[1] &= ~0x800; /* Off: #43 */
        _Pause[1] |= 0xc000; /* PauseOn: #46 #47 */
    } else {
        if (IS_SIGNAL(_Sig, __In_I_Configuration_Failure_112)) {
            EMIT(_Sig, __Out_O_RB_failure_code_127);
            if (!(IS_GUARD(7))) 
                _integer(&Out_O_RB_failure_code_127, RB_FAIL_INVALID_CONFIG);
            else
                _integer(&Out_O_RB_failure_code_127, INTEGER_COMBINE(Out_O_RB_failure_code_127, RB_FAIL_INVALID_CONFIG));
            SET_GUARD(7); 
            EMIT(_Sig, __Sig_sc_go_35_RbEstab_InitFailure_140);
            _On[1] |= 0x201000; /* On: #44 #53 */
            _On[1] &= ~0x800; /* Off: #43 */
        }
    }
}

static void Point_44(void) {
/*#44 */
    RRC_RG_O_O_RB_failure_code(Out_O_RB_failure_code_127); 
}

static void Point_45(void) {
/*#45 AutoPauseOn */
    if (IS_SIGNAL(_Sig, __In_I_CPHY_SYNCH_IND_99)) {
        if (_eq_integer(In_I_CPHY_SYNCH_IND_99, Sig_UE_Id_129)) {
            EMIT(_Sig, __Sig_sc_cond15_152);
            _On[1] &= ~0x2000; /* Off: #45 */
        } else {
            SET_GUARD(3); 
        }
    } else {
        SET_GUARD(3); 
    }
    if (IS_GUARD(3)) {
        if (IS_SIGNAL(_Sig, __In_I_CPHY_SYNCH_Failure_100)) {
            if (_eq_integer(In_I_CPHY_SYNCH_Failure_100, Sig_UE_Id_129)) {
                EMIT(_Sig, __Sig_sc_cond16_151);
                _On[1] &= ~0x2000; /* Off: #45 */
            }
        }
    }
}

static void Point_46(void) {
/*#46 AutoPauseOn */
    if (IS_SIGNAL(_Sig, __In_I_CPHY_RL_SETUP_Cnf_103)) {
        if (_eq_integer(In_I_CPHY_RL_SETUP_Cnf_103, Sig_UE_Id_129)) {
            EMIT(_Sig, __Sig_sc_cond12_144);
            _On[1] &= ~0x4000; /* Off: #46 */
        }
    }
}

static void Point_47(void) {
/*#47 AutoPauseOn */
    if (IS_SIGNAL(_Sig, __Sig_sc_cond12_144)) {
        encode_message(&Var_msg_139, Sig_UE_Id_129, RB_SETUP);
        EMIT(_Sig, __Out_O_SEND_DCCH_AM_120);
        if (!(IS_GUARD(14))) 
            _integer(&Out_O_SEND_DCCH_AM_120, Var_msg_139);
        else
            _integer(&Out_O_SEND_DCCH_AM_120, INTEGER_COMBINE(Out_O_SEND_DCCH_AM_120, Var_msg_139));
        SET_GUARD(14); 
        _On[1] |= 0x10000; /* On: #48 */
        _On[1] &= ~0x8000; /* Off: #47 */
        _Pause[1] |= 0x60000; /* PauseOn: #49 #50 */
        _Pause[1] &= ~0x4000; _On[1] &= ~0x4000; /* PauseOff: #46 */
    }
}

static void Point_48(void) {
/*#48 */
    RRC_RG_O_O_SEND_DCCH_AM(Out_O_SEND_DCCH_AM_120); 
}

static void Point_49(void) {
/*#49 AutoPauseOn */
    if (IS_SIGNAL(_Sig, __In_I_RLC_Success_106)) {
        if (_eq_integer(In_I_RLC_Success_106, Sig_UE_Id_129)) {
            EMIT(_Sig, __Sig_sc_cond13_148);
            _On[1] &= ~0x20000; /* Off: #49 */
        } else {
            SET_GUARD(4); 
        }
    } else {
        SET_GUARD(4); 
    }
    if (IS_GUARD(4)) {
        if (IS_SIGNAL(_Sig, __In_I_RLC_Failure_107)) {
            if (_eq_integer(In_I_RLC_Failure_107, Sig_UE_Id_129)) {
                EMIT(_Sig, __Sig_sc_cond14_147);
                _On[1] &= ~0x20000; /* Off: #49 */
            }
        }
    }
}

static void Point_50(void) {
/*#50 AutoPauseOn */
    if (IS_SIGNAL(_Sig, __Sig_sc_cond13_148)) {
        SET_GUARD(5); 
        EMIT(_Sig, __Sig_sc_go_34_RbEstab_Ack_142);
        _On[1] &= ~0x40000; /* Off: #50 */
    } else {
        if (IS_SIGNAL(_Sig, __Sig_sc_cond14_147)) {
            SET_GUARD(5); 
            EMIT(_Sig, __Sig_sc_go_41_RbEstab_fail_141);
            _On[1] &= ~0x40000; /* Off: #50 */
        }
    }
    if (IS_GUARD(5)) {
        _Pause[1] &= ~0x20000; _On[1] &= ~0x20000; /* PauseOff: #49 */
        if (IS_SIGNAL(_Sig, __Sig_sc_go_34_RbEstab_Ack_142)) {
            _Pause[1] |= 0x82000; /* PauseOn: #45 #51 */
        } else {
            _On[1] |= 0x100000; /* On: #52 */
        }
    }
}

static void Point_51(void) {
/*#51 AutoPauseOn */
    if (IS_SIGNAL(_Sig, __Sig_sc_cond15_152)) {
        SET_GUARD(6); 
        _On[1] &= ~0x80000; /* Off: #51 */
    } else {
        if (IS_SIGNAL(_Sig, __Sig_sc_cond16_151)) {
            SET_GUARD(6); 
            EMIT(_Sig, __Sig_sc_go_41_RbEstab_fail_141);
            _On[1] &= ~0x80000; /* Off: #51 */
        }
    }
    if (IS_GUARD(6)) {
        _On[1] |= 0x100000; /* On: #52 */
        _Pause[1] &= ~0x2000; _On[1] &= ~0x2000; /* PauseOff: #45 */
    }
}

static void Point_52(void) {
/*#52 */
    if (IS_SIGNAL(_Sig, __Sig_sc_go_41_RbEstab_fail_141)) {
        restore_former_config(Sig_UE_Id_129);
        EMIT(_Sig, __Out_O_NAS_RB_Failure_116);
        if (!(IS_GUARD(18))) 
            _integer(&Out_O_NAS_RB_Failure_116, Sig_UE_Id_129);
        else
            _integer(&Out_O_NAS_RB_Failure_116, INTEGER_COMBINE(Out_O_NAS_RB_Failure_116, Sig_UE_Id_129));
        SET_GUARD(18); 
        _On[1] |= 0x600000; /* On: #53 #54 */
    } else {
        _On[1] |= 0x200000; /* On: #53 */
    }
}

static void Point_53(void) {
/*#53 */
    if (IS_SIGNAL(_Sig, __Sig_sc_go_35_RbEstab_InitFailure_140)) {
        EMIT(_Sig, __Out_O_NAS_RB_Failure_116);
        if (!(IS_GUARD(18))) 
            _integer(&Out_O_NAS_RB_Failure_116, Sig_UE_Id_129);
        else
            _integer(&Out_O_NAS_RB_Failure_116, INTEGER_COMBINE(Out_O_NAS_RB_Failure_116, Sig_UE_Id_129));
        SET_GUARD(18); 
        _On[1] |= 0xc00000; /* On: #54 #55 */
    } else {
        _On[1] |= 0x800000; /* On: #55 */
    }
}

static void Point_54(void) {
/*#54 */
    RRC_RG_O_O_NAS_RB_Failure(Out_O_NAS_RB_Failure_116); 
}

static void Point_55(void) {
/*#55 */
    _Pause[0] |= 0x100; /* PauseOn: #8 */
}

static void Point_56(void) {
/*#56 */
    if (_eq_integer(Current_State(Sig_UE_Id_129), CELL_DCH_Connected)) {
        update_Mobile(Sig_UE_Id_129, CELL_DCH_Releasing);
        EMIT(_Sig, __Sig_sc_go_42_ConnRel_CFG_138);
    } else {
        if (_eq_integer(Current_State(Sig_UE_Id_129), CELL_FACH_Connected)) {
            update_Mobile(Sig_UE_Id_129, CELL_FACH_Releasing);
            EMIT(_Sig, __Sig_sc_go_42_ConnRel_CFG_138);
        }
    }
    if (IS_SIGNAL(_Sig, __Sig_sc_go_42_ConnRel_CFG_138)) {
        EMIT(_Sig, __Out_O_Action_125);
        if (!(IS_GUARD(9))) 
            _integer(&Out_O_Action_125, E_REL_MT);
        else
            _integer(&Out_O_Action_125, INTEGER_COMBINE(Out_O_Action_125, E_REL_MT));
        SET_GUARD(9); 
        EMIT(_Sig, __Out_O_Compute_Configuration_126);
        if (!(IS_GUARD(8))) 
            _integer(&Out_O_Compute_Configuration_126, Sig_UE_Id_129);
        else
            _integer(&Out_O_Compute_Configuration_126, INTEGER_COMBINE(Out_O_Compute_Configuration_126, Sig_UE_Id_129));
        SET_GUARD(8); 
        _On[2] |= 0x1000; /* On: #76 */
        _Pause[0] |= 0x20; /* PauseOn: #5 */
    } else {
        _On[1] |= 0x2000000; /* On: #57 */
    }
}

static void Point_57(void) {
/*#57 */
    if (IS_SIGNAL(_Sig, __Sig_sc_go_30_ConnRel_Send_136)) {
        encode_message(&Var_msg_137, Sig_UE_Id_129, RRC_CONN_RELEASE);
        EMIT(_Sig, __Out_O_SEND_DCCH_UM_119);
        if (!(IS_GUARD(15))) 
            _integer(&Out_O_SEND_DCCH_UM_119, Var_msg_137);
        else
            _integer(&Out_O_SEND_DCCH_UM_119, INTEGER_COMBINE(Out_O_SEND_DCCH_UM_119, Var_msg_137));
        SET_GUARD(15); 
        RRC_RG_O_O_SEND_DCCH_UM(Out_O_SEND_DCCH_UM_119); 
        _Pause[0] |= 0x40; /* PauseOn: #6 */
    } else {
        _Pause[0] |= 0x80; /* PauseOn: #7 */
    }
}

static void Point_58(void) {
/*#58 */
    if (_eq_integer(Current_State(Sig_UE_Id_129), CELL_DCH_Connecting)) {
        _On[1] |= 0x30000000; /* On: #60 #61 */
    } else {
        if (_eq_integer(Current_State(Sig_UE_Id_129), CELL_FACH_Connecting)) {
            update_Mobile(Sig_UE_Id_129, CELL_FACH_Connected);
            rg_clear_transaction(Sig_UE_Id_129, RRC_CONN_SETUP);
            _On[1] |= 0x8000000; /* On: #59 */
        } else {
            _Pause[0] |= 0x10; /* PauseOn: #4 */
        }
    }
}

static void Point_59(void) {
/*#59 */
    _Pause[0] |= 0x10; /* PauseOn: #4 */
}

static void Point_60(void) {
/*#60 */
    update_Mobile(Sig_UE_Id_129, CELL_DCH_Connected);
    rg_clear_transaction(Sig_UE_Id_129, RRC_CONN_SETUP);
}

static void Point_61(void) {
/*#61 */
    _Pause[0] |= 0x10; /* PauseOn: #4 */
}

static void Point_62(void) {
/*#62 */
    if (_eq_integer(Current_State(Sig_UE_Id_129), FAILURE)) {
        EMIT(_Sig, __Out_O_NAS_CONN_ESTAB_IND_113);
        _On[2] |= 0x3; /* On: #64 #65 */
    } else {
        if ((((_eq_integer(Current_State(Sig_UE_Id_129), CELL_DCH_Connected) || _eq_integer(Current_State(Sig_UE_Id_129), CELL_DCH_Connecting)) || _eq_integer(Current_State(Sig_UE_Id_129), CELL_FACH_Connected)) || _eq_integer(Current_State(Sig_UE_Id_129), CELL_FACH_Connecting))) {
            encode_message(&Var_msgReq_134, Sig_UE_Id_129, RRC_CONN_SETUP);
            EMIT(_Sig, __Out_O_SEND_CCCH_118);
            if (!(IS_GUARD(16))) 
                _integer(&Out_O_SEND_CCCH_118, Var_msgReq_134);
            else
                _integer(&Out_O_SEND_CCCH_118, INTEGER_COMBINE(Out_O_SEND_CCCH_118, Var_msgReq_134));
            SET_GUARD(16); 
            _On[1] |= 0x80000000; _On[2] |= 0x400; /* On: #63 #74 */
        } else {
            _Pause[0] |= 0x8; /* PauseOn: #3 */
        }
    }
}

static void Point_63(void) {
/*#63 */
    _Pause[0] |= 0x8; /* PauseOn: #3 */
}

static void Point_64(void) {
/*#64 */
    _integer(&Out_O_NAS_CONN_ESTAB_IND_113, Sig_UE_Id_129);
    create_Mobile(Sig_UE_Id_129);
    RRC_RG_O_O_NAS_CONN_ESTAB_IND(Out_O_NAS_CONN_ESTAB_IND_113); 
}

static void Point_65(void) {
/*#65 */
    _Pause[0] |= 0x8; /* PauseOn: #3 */
}

static void Point_66(void) {
/*#66 */
    if (_eq_integer(Current_State(Sig_UE_Id_129), Conn_Received)) {
        if (_eq_integer(In_I_Status_108, SUCCESS)) {
            if (IS_SIGNAL(_Sig, __In_I_RB_List_109)) {
                proc_RB_List(&Var_msg_132, In_I_RB_List_109, Sig_UE_Id_129);
                update_Mobile(Sig_UE_Id_129, CELL_DCH_Connecting);
                _Pause[2] |= 0x8; /* PauseOn: #67 */
            } else {
                update_Mobile(Sig_UE_Id_129, CELL_FACH_Connecting);
                _Pause[2] |= 0x8; /* PauseOn: #67 */
            }
            EMIT(_Sig, __Out_O_Action_125);
            if (!(IS_GUARD(9))) 
                _integer(&Out_O_Action_125, E_ADD_MT);
            else
                _integer(&Out_O_Action_125, INTEGER_COMBINE(Out_O_Action_125, E_ADD_MT));
            SET_GUARD(9); 
            EMIT(_Sig, __Out_O_Compute_Configuration_126);
            if (!(IS_GUARD(8))) 
                _integer(&Out_O_Compute_Configuration_126, Sig_UE_Id_129);
            else
                _integer(&Out_O_Compute_Configuration_126, INTEGER_COMBINE(Out_O_Compute_Configuration_126, Sig_UE_Id_129));
            SET_GUARD(8); 
            _On[2] |= 0x1000; /* On: #76 */
        } else {
            EMIT(_Sig, __Sig_sc_go_26_ConnEstab_REJECT_133);
            _On[2] |= 0x100; /* On: #72 */
        }
    } else {
        _Pause[0] |= 0x4; /* PauseOn: #2 */
    }
}

static void Point_67(void) {
/*#67 AutoPauseOn */
    if (IS_SIGNAL(_Sig, __In_I_Configuration_Indication_111)) {
        EMIT(_Sig, __Out_O_CPHY_RL_SETUP_Req_121);
        if (!(IS_GUARD(13))) { RRC_RG_O_O_CPHY_RL_SETUP_Req(); SET_GUARD(13); }
        EMIT(_Sig, __Out_O_CRLC_CONFIG_Req_124);
        if (!(IS_GUARD(10))) { RRC_RG_O_O_CRLC_CONFIG_Req(); SET_GUARD(10); }
        _On[2] |= 0x10; /* On: #68 */
        _On[2] &= ~0x8; /* Off: #67 */
    } else {
        if (IS_SIGNAL(_Sig, __In_I_Configuration_Failure_112)) {
            EMIT(_Sig, __Out_O_NAS_CONN_RELEASE_IND_114);
            _On[2] |= 0x20; /* On: #69 */
            _On[2] &= ~0x8; /* Off: #67 */
        }
    }
}

static void Point_68(void) {
/*#68 */
    EMIT(_Sig, __Out_O_CMAC_CONFIG_Req_123);
    if (!(IS_GUARD(11))) { RRC_RG_O_O_CMAC_CONFIG_Req(); SET_GUARD(11); }
    _On[2] |= 0x40; /* On: #70 */
    _Pause[0] |= 0x2; /* PauseOn: #1 */
}

static void Point_69(void) {
/*#69 */
    if (!(IS_GUARD(19))) 
        _integer(&Out_O_NAS_CONN_RELEASE_IND_114, Sig_UE_Id_129);
    else
        _integer(&Out_O_NAS_CONN_RELEASE_IND_114, INTEGER_COMBINE(Out_O_NAS_CONN_RELEASE_IND_114, Sig_UE_Id_129));
    SET_GUARD(19); 
    EMIT(_Sig, __Sig_sc_go_26_ConnEstab_REJECT_133);
    _On[2] |= 0x180; /* On: #71 #72 */
}

static void Point_70(void) {
/*#70 */
    encode_message(&Var_msg_132, Sig_UE_Id_129, RRC_CONN_SETUP);
    EMIT(_Sig, __Out_O_SEND_CCCH_118);
    if (!(IS_GUARD(16))) 
        _integer(&Out_O_SEND_CCCH_118, Var_msg_132);
    else
        _integer(&Out_O_SEND_CCCH_118, INTEGER_COMBINE(Out_O_SEND_CCCH_118, Var_msg_132));
    SET_GUARD(16); 
    _On[2] |= 0x400; /* On: #74 */
}

static void Point_71(void) {
/*#71 */
    RRC_RG_O_O_NAS_CONN_RELEASE_IND(Out_O_NAS_CONN_RELEASE_IND_114); 
}

static void Point_72(void) {
/*#72 */
    if (IS_SIGNAL(_Sig, __Sig_sc_go_26_ConnEstab_REJECT_133)) {
        _On[2] |= 0x200; /* On: #73 */
    } else {
        _Pause[0] |= 0x4; /* PauseOn: #2 */
    }
}

static void Point_73(void) {
/*#73 */
    encode_message(&Var_msg_132, Sig_UE_Id_129, RRC_CONN_REJECT);
    EMIT(_Sig, __Out_O_SEND_CCCH_118);
    if (!(IS_GUARD(16))) 
        _integer(&Out_O_SEND_CCCH_118, Var_msg_132);
    else
        _integer(&Out_O_SEND_CCCH_118, INTEGER_COMBINE(Out_O_SEND_CCCH_118, Var_msg_132));
    SET_GUARD(16); 
    EMIT(_Sig, __Sig_Conn_Establish_complete_128);
    _On[2] |= 0xc00; /* On: #74 #75 */
}

static void Point_74(void) {
/*#74 */
    RRC_RG_O_O_SEND_CCCH(Out_O_SEND_CCCH_118); 
}

static void Point_75(void) {
/*#75 AutoPauseOn */
    if (IS_SIGNAL(_Sig, __Sig_Conn_Establish_complete_128)) {
        delete_Mobile(Sig_UE_Id_129);
        _On[2] &= ~0x800; /* Off: #75 */
        _Pause[0] |= 0x4; /* PauseOn: #2 */
    }
}

static void Point_76(void) {
/*#76 */
    RRC_RG_O_O_Action(Out_O_Action_125); 
    RRC_RG_O_O_Compute_Configuration(Out_O_Compute_Configuration_126); 
}


int RRC_RG(void)
{
    unsigned int *Points;

    Points = _On;
    if (*Points) {
        if (*Points & 0x1) {
            Point_0();
        }
        if (*Points & 0x2) {
            Point_1();
        }
        if (*Points & 0x4) {
            Point_2();
        }
        if (*Points & 0x8) {
            Point_3();
        }
        if (*Points & 0x10) {
            Point_4();
        }
        if (*Points & 0x20) {
            Point_5();
        }
        if (*Points & 0x40) {
            Point_6();
        }
        if (*Points & 0x80) {
            Point_7();
        }
        if (*Points & 0x100) {
            Point_8();
        }
        if (*Points & 0x200) {
            Point_9();
        }
        if (*Points & 0x400) {
            Point_10();
        }
        if (*Points & 0x800) {
            Point_11();
        }
        if (*Points & 0x1000) {
            Point_12();
        }
        if (*Points & 0x2000) {
            Point_13();
        }
        if (*Points & 0x4000) {
            Point_14();
        }
        if (*Points & 0x8000) {
            Point_15();
        }
        if (*Points & 0x10000) {
            Point_16();
        }
        if (*Points & 0x20000) {
            Point_17();
        }
        if (*Points & 0x40000) {
            Point_18();
        }
        if (*Points & 0x80000) {
            Point_19();
        }
        if (*Points & 0x100000) {
            Point_20();
        }
        if (*Points & 0x200000) {
            Point_21();
        }
        if (*Points & 0x400000) {
            Point_22();
        }
        if (*Points & 0x800000) {
            Point_23();
        }
        if (*Points & 0x1000000) {
            Point_24();
        }
        if (*Points & 0x2000000) {
            Point_25();
        }
        if (*Points & 0x4000000) {
            Point_26();
        }
        if (*Points & 0x8000000) {
            Point_27();
        }
        if (*Points & 0x10000000) {
            Point_28();
        }
        if (*Points & 0x20000000) {
            Point_29();
        }
        if (*Points & 0x40000000) {
            Point_30();
        }
        if (*Points & 0x80000000) {
            Point_31();
        }
    }
    Points++;
    if (*Points) {
        if (*Points & 0x1) {
            Point_32();
        }
        if (*Points & 0x2) {
            Point_33();
        }
        if (*Points & 0x4) {
            Point_34();
        }
        if (*Points & 0x8) {
            Point_35();
        }
        if (*Points & 0x10) {
            Point_36();
        }
        if (*Points & 0x20) {
            Point_37();
        }
        if (*Points & 0x40) {
            Point_38();
        }
        if (*Points & 0x80) {
            Point_39();
        }
        if (*Points & 0x100) {
            Point_40();
        }
        if (*Points & 0x200) {
            Point_41();
        }
        if (*Points & 0x400) {
            Point_42();
        }
        if (*Points & 0x800) {
            Point_43();
        }
        if (*Points & 0x1000) {
            Point_44();
        }
        if (*Points & 0x2000) {
            Point_45();
        }
        if (*Points & 0x4000) {
            Point_46();
        }
        if (*Points & 0x8000) {
            Point_47();
        }
        if (*Points & 0x10000) {
            Point_48();
        }
        if (*Points & 0x20000) {
            Point_49();
        }
        if (*Points & 0x40000) {
            Point_50();
        }
        if (*Points & 0x80000) {
            Point_51();
        }
        if (*Points & 0x100000) {
            Point_52();
        }
        if (*Points & 0x200000) {
            Point_53();
        }
        if (*Points & 0x400000) {
            Point_54();
        }
        if (*Points & 0x800000) {
            Point_55();
        }
        if (*Points & 0x1000000) {
            Point_56();
        }
        if (*Points & 0x2000000) {
            Point_57();
        }
        if (*Points & 0x4000000) {
            Point_58();
        }
        if (*Points & 0x8000000) {
            Point_59();
        }
        if (*Points & 0x10000000) {
            Point_60();
        }
        if (*Points & 0x20000000) {
            Point_61();
        }
        if (*Points & 0x40000000) {
            Point_62();
        }
        if (*Points & 0x80000000) {
            Point_63();
        }
    }
    Points++;
    if (*Points) {
        if (*Points & 0x1) {
            Point_64();
        }
        if (*Points & 0x2) {
            Point_65();
        }
        if (*Points & 0x4) {
            Point_66();
        }
        if (*Points & 0x8) {
            Point_67();
        }
        if (*Points & 0x10) {
            Point_68();
        }
        if (*Points & 0x20) {
            Point_69();
        }
        if (*Points & 0x40) {
            Point_70();
        }
        if (*Points & 0x80) {
            Point_71();
        }
        if (*Points & 0x100) {
            Point_72();
        }
        if (*Points & 0x200) {
            Point_73();
        }
        if (*Points & 0x400) {
            Point_74();
        }
        if (*Points & 0x800) {
            Point_75();
        }
        if (*Points & 0x1000) {
            Point_76();
        }
    }
    Points++;
    {
        int j;

        for (j = 0; j < SIGNAL_VECTOR_SIZE; j++) _Sig[j] = 0;
        Sig_Rel_repeat_135_Pre1 = Sig_Rel_repeat_135_Pre0 ;
        _On[0] = _Pause[0] | (_On[0] & 0xd8ffbe);
        _On[1] = _Pause[1] | (_On[1] & 0xee9c0);
        _On[2] = _Pause[2] | (_On[2] & 0x808);
        /* AutoPauseOn: #1 #2 #3 #4 #5 #7 #8 #9 #10 #11 #12 #13 #14 #15 #19 #20 #22 #23 #38 #39 #40 #43 #45 #46 #47 #49 #50 #51 #67 #75 */
        for (j = 0; j < HALT_POINT_VECTOR_SIZE; j++) _Pause[j] = 0;
        for (j = 0; j < GUARD_VECTOR_SIZE; j++) _Guard[j] = 0;
    }
    return Var__ThisIsTheEnd__171;
}

int RRC_RG_reset(void) {
    int i,j;

    for (j = 0 ; j < SIGNAL_VECTOR_SIZE; j++) _Sig[j] = 0;
    for (i = 0 ; i < HALT_POINT_VECTOR_SIZE; i++) _On[i] = 0;
    for (i = 0 ; i < HALT_POINT_VECTOR_SIZE; i++) _Pause[i] = 0;
    for (i = 0 ; i < GUARD_VECTOR_SIZE; i++) _Guard[i] = 0;
    BIT_SET(_On, 0);
    return 1;
}

typedef int (*SimInitFunc_t) ();
int RRC_RG_init (char** pError, SimInitFunc_t pFunc) {
   return 1;
}
typedef int (*SimEndFunc_t) ();
int RRC_RG_end (SimEndFunc_t pFunc) {
   return 1;
}
int RRC_RG_run(void) {
   return RRC_RG();
}
int RRC_RG_getError(void) {
   return 0;
}
char* RRC_RG_getErrorMessage(void) {
   return (char*)0;
}
