/* Form definition file generated by fdesign */

#include <stdlib.h>
#include "lte_scope.h"


/***************************************
 ***************************************/

FD_lte_scope *
create_form_lte_scope( void )
{
    FL_OBJECT *obj;
    FD_lte_scope *fdui = fl_malloc( sizeof *fdui );

    fdui->vdata = fdui->cdata = NULL;
    fdui->ldata = 0;

    fdui->lte_scope = fl_bgn_form( FL_NO_BOX, 780, 723 );

    obj = fl_add_box( FL_ROUNDED_BOX, 0, 0, 780, 723, "" );
    fl_set_object_color( obj, FL_BLACK, FL_BLUE );

    fdui->channel_t_re = obj = fl_add_xyplot( FL_NORMAL_XYPLOT, 20, 20, 280, 100, "Received Signal (Time-Domain, dB)" );
    fl_set_object_boxtype( obj, FL_EMBOSSED_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_BLUE );
    fl_set_object_lcolor( obj, FL_WHITE );

    fdui->scatter_plot = obj = fl_add_xyplot( FL_POINTS_XYPLOT, 600, 230, 160, 190, "PBCH Scatter Plot" );
    fl_set_object_boxtype( obj, FL_EMBOSSED_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_GREEN );
    fl_set_object_lcolor( obj, FL_WHITE );

    fdui->channel_f = obj = fl_add_xyplot( FL_IMPULSE_XYPLOT, 20, 140, 570, 90, "Frequency Domain Channel Estimate" );
    fl_set_object_boxtype( obj, FL_EMBOSSED_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_RED );
    fl_set_object_lcolor( obj, FL_WHITE );

    fdui->channel_t_im = obj = fl_add_xyplot( FL_NORMAL_XYPLOT, 310, 20, 280, 100, "Time-Domain Channel Estimate" );
    fl_set_object_boxtype( obj, FL_EMBOSSED_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_BLUE );
    fl_set_object_lcolor( obj, FL_WHITE );

    fdui->decoder_input = obj = fl_add_xyplot( FL_POINTS_XYPLOT, 20, 250, 570, 130, "PBCH Decoder Input" );
    fl_set_object_boxtype( obj, FL_EMBOSSED_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_GREEN );
    fl_set_object_lcolor( obj, FL_WHITE );

    fdui->scatter_plot2 = obj = fl_add_xyplot( FL_POINTS_XYPLOT, 600, 440, 160, 190, "PDSCH/PUSCH Scatter Plot" );
    fl_set_object_boxtype( obj, FL_EMBOSSED_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_lcolor( obj, FL_WHITE );

    fdui->scatter_plot1 = obj = fl_add_xyplot( FL_POINTS_XYPLOT, 600, 20, 160, 190, "PDCCH Scatter Plot" );
    fl_set_object_boxtype( obj, FL_EMBOSSED_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_CYAN );
    fl_set_object_lcolor( obj, FL_WHITE );

    fdui->ia_receiver_button = obj = fl_add_button( FL_PUSH_BUTTON, 620, 660, 130, 40, "IA receiver OFF" );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_color( obj, FL_RED, FL_BLACK);
    //    fl_set_object_callback( obj, ia_receiver_on_off, 0 );

    fdui->demod_out = obj = fl_add_xyplot( FL_POINTS_XYPLOT, 20, 400, 570, 140, "PDSCH/PUSCH Decoder Input" );
    fl_set_object_boxtype( obj, FL_EMBOSSED_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_lcolor( obj, FL_WHITE );

    fdui->tput = obj = fl_add_xyplot( FL_NORMAL_XYPLOT, 20, 560, 570, 140, "Throughput [kbits/s]" );
    fl_set_object_boxtype( obj, FL_EMBOSSED_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_WHITE );
    fl_set_object_lcolor( obj, FL_WHITE );

    fl_end_form( );

    fdui->lte_scope->fdui = fdui;

    return fdui;
}
