/* Header file generated by fdesign on Tue Nov 13 09:42:50 2012 */

#ifndef FD_lte_scope_h_
#define FD_lte_scope_h_

#include <forms.h>

/* Callbacks, globals and object handlers */

extern void ia_receiver_on_off( FL_OBJECT *, long );


/* Forms and Objects */

typedef struct {
    FL_FORM   * lte_scope;
    void      * vdata;
    char      * cdata;
    long        ldata;
    FL_OBJECT * channel_t_re[4];
    FL_OBJECT * channel_t_im[4];
  /*
    FL_OBJECT * scatter_plot;
    FL_OBJECT * channel_f;
    FL_OBJECT * decoder_input;
    FL_OBJECT * scatter_plot2;
    FL_OBJECT * scatter_plot1;
    FL_OBJECT * ia_receiver_button;
    FL_OBJECT * demod_out;
    FL_OBJECT * tput;
  */
} FD_lte_scope;

extern FD_lte_scope * create_form_lte_scope( void );

#endif /* FD_lte_scope_h_ */
