/* Form definition file generated by fdesign */

#include <stdlib.h>
#include "lte_scope.h"


/***************************************
 ***************************************/

FD_lte_scope *
create_form_lte_scope( void )
{
    FL_OBJECT *obj;
    FD_lte_scope *fdui = fl_malloc( sizeof *fdui );

    fdui->vdata = fdui->cdata = NULL;
    fdui->ldata = 0;

    fdui->lte_scope = fl_bgn_form( FL_NO_BOX, 780, 723 );

    obj = fl_add_box( FL_ROUNDED_BOX, 0, 0, 780, 723, "" );
    fl_set_object_color( obj, FL_BLACK, FL_BLUE );

    fdui->channel_t_re[0] = obj = fl_add_xyplot( FL_NORMAL_XYPLOT, 20, 20, 280, 100, "Real(RX0)" );
    fl_set_object_boxtype( obj, FL_EMBOSSED_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_BLUE );
    fl_set_object_lcolor( obj, FL_WHITE );

    fdui->channel_t_im[0] = obj = fl_add_xyplot( FL_NORMAL_XYPLOT, 310, 20, 280, 100, "Imag(RX0)" );
    fl_set_object_boxtype( obj, FL_EMBOSSED_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_BLUE );
    fl_set_object_lcolor( obj, FL_WHITE );

    fdui->channel_t_re[1] = obj = fl_add_xyplot( FL_NORMAL_XYPLOT, 20, 140, 280, 100, "Real(RX1)" );
    fl_set_object_boxtype( obj, FL_EMBOSSED_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_RED );
    fl_set_object_lcolor( obj, FL_WHITE );

    fdui->channel_t_im[1] = obj = fl_add_xyplot( FL_NORMAL_XYPLOT, 310, 140, 280, 100, "Imag(RX1)" );
    fl_set_object_boxtype( obj, FL_EMBOSSED_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_RED );
    fl_set_object_lcolor( obj, FL_WHITE );

    fdui->channel_t_re[2] = obj = fl_add_xyplot( FL_NORMAL_XYPLOT, 20, 260, 280, 100, "Real(RX2)" );
    fl_set_object_boxtype( obj, FL_EMBOSSED_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_GREEN );
    fl_set_object_lcolor( obj, FL_WHITE );

    fdui->channel_t_im[2] = obj = fl_add_xyplot( FL_NORMAL_XYPLOT, 310, 260, 280, 100, "Imag(RX2)" );
    fl_set_object_boxtype( obj, FL_EMBOSSED_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_GREEN );
    fl_set_object_lcolor( obj, FL_WHITE );

    fdui->channel_t_re[3] = obj = fl_add_xyplot( FL_NORMAL_XYPLOT, 20, 380, 280, 100, "Real(RX3)" );
    fl_set_object_boxtype( obj, FL_EMBOSSED_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_lcolor( obj, FL_WHITE );

    fdui->channel_t_im[3] = obj = fl_add_xyplot( FL_NORMAL_XYPLOT, 310, 380, 280, 100, "Imag(RX3)" );
    fl_set_object_boxtype( obj, FL_EMBOSSED_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_lcolor( obj, FL_WHITE );

    /*
    fdui->scatter_plot = obj = fl_add_xyplot( FL_POINTS_XYPLOT, 600, 230, 160, 190, "PBCH Scatter Plot" );
    fl_set_object_boxtype( obj, FL_EMBOSSED_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_GREEN );
    fl_set_object_lcolor( obj, FL_WHITE );

    fdui->scatter_plot2 = obj = fl_add_xyplot( FL_POINTS_XYPLOT, 600, 440, 160, 190, "PDSCH/PUSCH Scatter Plot" );
    fl_set_object_boxtype( obj, FL_EMBOSSED_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_lcolor( obj, FL_WHITE );

    fdui->scatter_plot1 = obj = fl_add_xyplot( FL_POINTS_XYPLOT, 600, 20, 160, 190, "PDCCH Scatter Plot" );
    fl_set_object_boxtype( obj, FL_EMBOSSED_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_CYAN );
    fl_set_object_lcolor( obj, FL_WHITE );

    fdui->ia_receiver_button = obj = fl_add_button( FL_PUSH_BUTTON, 620, 660, 130, 40, "IA receiver OFF" );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_color( obj, FL_RED, FL_RED);
    fl_set_object_callback( obj, ia_receiver_on_off, 0 );

    fdui->tput = obj = fl_add_xyplot( FL_NORMAL_XYPLOT, 20, 560, 570, 140, "Throughput [kbits/s]" );
    fl_set_object_boxtype( obj, FL_EMBOSSED_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_WHITE );
    fl_set_object_lcolor( obj, FL_WHITE );
    */

    fl_end_form( );

    fdui->lte_scope->fdui = fdui;

    return fdui;
}
