S1AP_ASN_MODULE_SOURCES= \
    Criticality.o   \
    Presence.o  \
    PrivateIE-ID.o  \
    ProcedureCode.o \
    ProtocolExtensionID.o   \
    ProtocolIE-ID.o \
    TriggeringMessage.o \
    IE-Extensions.o \
    AllocationAndRetentionPriority.o    \
    Bearers-SubjectToStatusTransfer-List.o   \
    Bearers-SubjectToStatusTransfer-Item.o  \
    BitRate.o   \
    BPLMNs.o    \
    BroadcastCompletedAreaList.o    \
    Cause.o \
    CauseMisc.o \
    CauseProtocol.o \
    CauseRadioNetwork.o \
    CauseTransport.o    \
    CauseNas.o  \
    CellIdentity.o  \
    CellID-Broadcast.o  \
    CellID-Broadcast-Item.o \
    Cdma2000PDU.o   \
    Cdma2000RATType.o   \
    Cdma2000SectorID.o  \
    Cdma2000HOStatus.o  \
    Cdma2000HORequiredIndication.o  \
    Cdma2000OneXSRVCCInfo.o \
    Cdma2000OneXMEID.o  \
    Cdma2000OneXMSI.o   \
    Cdma2000OneXPilot.o \
    Cdma2000OneXRAND.o  \
    Cell-Size.o \
    CellType.o  \
    CGI.o   \
    CI.o    \
    CNDomain.o  \
    CSFallbackIndicator.o   \
    CSG-Id.o    \
    CSG-IdList.o    \
    CSG-IdList-Item.o   \
    COUNTvalue.o    \
    CriticalityDiagnostics.o    \
    CriticalityDiagnostics-IE-List.o    \
    CriticalityDiagnostics-IE-Item.o    \
    DataCodingScheme.o  \
    DL-Forwarding.o \
    Direct-Forwarding-Path-Availability.o   \
    E-RABToBeModifiedListBearerModReq.o \
    E-RABToBeModifiedItemBearerModReq.o \
    E-RABReleaseListBearerRelComp.o \
    E-RABReleaseItemBearerRelComp.o \
    E-RABDataForwardingList.o   \
    E-RABDataForwardingItem.o   \
    E-RABToBeSetupListCtxtSUReq.o   \
    E-RABToBeSetupItemCtxtSUReq.o   \
    E-RABSetupListBearerSURes.o \
    E-RABSetupItemBearerSURes.o \
    E-RABFailedtoSetupListHOReqAck.o    \
    E-RABFailedToSetupItemHOReqAck.o    \
    E-RABToBeSetupListBearerSUReq.o \
    E-RABToBeSetupItemBearerSUReq.o \
    E-RABAdmittedList.o \
    E-RABAdmittedItem.o \
    E-RABToBeSwitchedDLList.o   \
    E-RABToBeSwitchedDLItem.o   \
    E-RABToBeSwitchedULList.o   \
    E-RABToBeSwitchedULItem.o   \
    E-RABModifyListBearerModRes.o   \
    E-RABModifyItemBearerModRes.o   \
    E-RABSetupListCtxtSURes.o   \
    E-RABSetupItemCtxtSURes.o   \
    E-RABToBeSetupListHOReq.o   \
    E-RABToBeSetupItemHOReq.o   \
    ECGIList.o  \
    EmergencyAreaIDList.o   \
    EmergencyAreaID.o   \
    EmergencyAreaID-Broadcast.o \
    EmergencyAreaID-Broadcast-Item.o    \
    CompletedCellinEAI.o    \
    CompletedCellinEAI-Item.o   \
    ENB-ID.o    \
    GERAN-Cell-ID.o \
    Global-ENB-ID.o \
    ENB-StatusTransfer-TransparentContainer.o   \
    ENB-UE-S1AP-ID.o    \
    ENBname.o   \
    ENBX2TLAs.o \
    EncryptionAlgorithms.o  \
    EPLMNs.o    \
    EventType.o \
    E-RAB-ID.o  \
    E-RABInformationList.o  \
    E-RABInformationListItem.o  \
    E-RABList.o \
    E-RABItem.o \
    E-RABLevelQoSParameters.o   \
    EUTRAN-CGI.o    \
    ExtendedRNC-ID.o    \
    ForbiddenInterRATs.o    \
    ForbiddenTAs.o  \
    ForbiddenTAs-Item.o \
    ForbiddenTACs.o \
    ForbiddenLAs.o  \
    ForbiddenLAs-Item.o \
    ForbiddenLACs.o \
    GBR-QosInformation.o    \
    GTP-TEID.o  \
    GUMMEI.o    \
    HandoverRestrictionList.o   \
    HandoverType.o  \
    HFN.o   \
    Inter-SystemInformationTransferType.o   \
    IMSI.o  \
    IntegrityProtectionAlgorithms.o \
    InterfacesToTrace.o \
    LAC.o   \
    LAI.o   \
    LastVisitedCell-Item.o  \
    LastVisitedEUTRANCellInformation.o  \
    LastVisitedUTRANCellInformation.o   \
    LastVisitedGERANCellInformation.o   \
    L3-Information.o    \
    MessageIdentifier.o \
    MMEname.o   \
    MME-Group-ID.o  \
    MME-Code.o  \
    MME-UE-S1AP-ID.o    \
    M-TMSI.o    \
    MSClassmark2.o  \
    MSClassmark3.o  \
    NAS-PDU.o   \
    NASSecurityParametersfromE-UTRAN.o  \
    NASSecurityParameterstoE-UTRAN.o    \
    NumberofBroadcastRequest.o  \
    NumberOfBroadcasts.o \
    OldBSS-ToNewBSS-Information.o   \
    OverloadAction.o    \
    OverloadResponse.o  \
    PagingDRX.o \
    PDCP-SN.o   \
    PLMNidentity.o  \
    Pre-emptionCapability.o \
    Pre-emptionVulnerability.o  \
    PriorityLevel.o \
    QCI.o   \
    ReceiveStatusofULPDCPSDUs.o \
    RelativeMMECapacity.o   \
    RAC.o   \
    RequestType.o   \
    ResetType.o \
    ResetAll.o  \
    RIMTransfer.o   \
    RIMInformation.o    \
    RIMRoutingAddress.o \
    ReportArea.o    \
    RepetitionPeriod.o  \
    RNC-ID.o    \
    RRC-Container.o \
    RRC-Establishment-Cause.o   \
    SecurityKey.o   \
    SecurityContext.o   \
    SerialNumber.o  \
    SONInformation.o    \
    SONInformationRequest.o \
    SONInformationReply.o   \
    SONConfigurationTransfer.o  \
    Source-ToTarget-TransparentContainer.o  \
    SourceBSS-ToTargetBSS-TransparentContainer.o    \
    SourceeNB-ID.o  \
    SRVCCOperationPossible.o    \
    SRVCCHOIndication.o \
    SourceeNB-ToTargeteNB-TransparentContainer.o    \
    SourceRNC-ToTargetRNC-TransparentContainer.o    \
    ServedGUMMEIs.o \
    ServedGUMMEIsItem.o \
    ServedGroupIDs.o    \
    ServedMMECs.o   \
    ServedPLMNs.o   \
    SubscriberProfileIDforRFP.o \
    SupportedTAs.o  \
    SupportedTAs-Item.o \
    S-TMSI.o    \
    TAC.o   \
    TAIListforWarning.o \
    TAIList.o   \
    TAIItem.o   \
    TAI.o   \
    TAI-Broadcast.o \
    TAI-Broadcast-Item.o    \
    CompletedCellinTAI.o    \
    CompletedCellinTAI-Item.o   \
    TBCD-STRING.o   \
    TargetID.o  \
    TargeteNB-ID.o  \
    TargetRNC-ID.o  \
    TargeteNB-ToSourceeNB-TransparentContainer.o    \
    Target-ToSource-TransparentContainer.o  \
    TargetRNC-ToSourceRNC-TransparentContainer.o    \
    TargetBSS-ToSourceBSS-TransparentContainer.o    \
    TimeToWait.o    \
    Time-UE-StayedInCell.o  \
    TransportLayerAddress.o \
    TraceActivation.o   \
    TraceDepth.o    \
    E-UTRAN-Trace-ID.o  \
    TypeOfError.o   \
    UEAggregateMaximumBitrate.o \
    UE-S1AP-IDs.o   \
    UE-S1AP-ID-pair.o   \
    UE-associatedLogicalS1-ConnectionListRes.o  \
    UE-associatedLogicalS1-ConnectionListResAck.o   \
    UE-associatedLogicalS1-ConnectionItem.o \
    UEIdentityIndexValue.o  \
    UE-HistoryInformation.o \
    UEPagingID.o    \
    UERadioCapability.o \
    UESecurityCapabilities.o    \
    WarningAreaList.o   \
    WarningType.o   \
    WarningSecurityInfo.o   \
    WarningMessageContents.o    \
    X2TNLConfigurationInfo.o    \
    S1AP-PDU.o  \
    InitiatingMessage.o \
    SuccessfulOutcome.o \
    UnsuccessfulOutcome.o   \
    HandoverRequired.o  \
    HandoverCommand.o   \
    HandoverPreparationFailure.o    \
    HandoverRequest.o   \
    HandoverRequestAcknowledge.o    \
    HandoverFailure.o   \
    HandoverNotify.o \
    PathSwitchRequest.o \
    PathSwitchRequestAcknowledge.o  \
    PathSwitchRequestFailure.o  \
    E-RABSetupRequest.o \
    E-RABSetupResponse.o    \
    E-RABModifyRequest.o    \
    E-RABModifyResponse.o   \
    E-RABReleaseIndication.o    \
    E-RABReleaseCommand.o   \
    E-RABReleaseResponse.o  \
    InitialContextSetupRequest.o    \
    InitialContextSetupResponse.o   \
    InitialContextSetupFailure.o    \
    UEContextReleaseRequest.o   \
    Paging.o    \
    DownlinkNASTransport.o  \
    InitialUEMessage.o  \
    UplinkNASTransport.o    \
    NASNonDeliveryIndication.o  \
    HandoverCancel.o    \
    HandoverCancelAcknowledge.o \
    Reset.o \
    ResetAcknowledge.o  \
    S1SetupResponse.o   \
    S1SetupRequest.o    \
    S1SetupFailure.o    \
    ErrorIndication.o   \
    ENBConfigurationUpdate.o    \
    ENBConfigurationUpdateAcknowledge.o \
    ENBConfigurationUpdateFailure.o \
    MMEConfigurationUpdate.o    \
    MMEConfigurationUpdateAcknowledge.o \
    MMEConfigurationUpdateFailure.o \
    DownlinkS1cdma2000tunneling.o   \
    UplinkS1cdma2000tunneling.o \
    UEContextModificationRequest.o  \
    UEContextModificationResponse.o \
    UEContextModificationFailure.o  \
    UECapabilityInfoIndication.o    \
    UEContextReleaseCommand.o   \
    UEContextReleaseComplete.o  \
    ENBStatusTransfer.o \
    MMEStatusTransfer.o \
    DeactivateTrace.o   \
    TraceStart.o    \
    TraceFailureIndication.o    \
    CellTrafficTrace.o  \
    LocationReportingControl.o  \
    LocationReportingFailureIndication.o    \
    LocationReport.o    \
    OverloadStart.o \
    OverloadStop.o  \
    WriteReplaceWarningRequest.o    \
    WriteReplaceWarningResponse.o   \
    ENBDirectInformationTransfer.o  \
    MMEDirectInformationTransfer.o  \
    ENBConfigurationTransfer.o  \
    MMEConfigurationTransfer.o  \
    PrivateMessage.o    \
    IE.o

S1AP_ASN_MODULE_HEADERS= \
    Criticality.h   \
    Presence.h  \
    PrivateIE-ID.h  \
    ProcedureCode.h \
    ProtocolExtensionID.h   \
    ProtocolIE-ID.h \
    TriggeringMessage.h \
    IE-Extensions.h \
    AllocationAndRetentionPriority.h    \
    Bearers-SubjectToStatusTransfer-List.h   \
    Bearers-SubjectToStatusTransfer-Item.h  \
    BitRate.h   \
    BPLMNs.h    \
    BroadcastCompletedAreaList.h    \
    Cause.h \
    CauseMisc.h \
    CauseProtocol.h \
    CauseRadioNetwork.h \
    CauseTransport.h    \
    CauseNas.h  \
    CellIdentity.h  \
    CellID-Broadcast.h  \
    CellID-Broadcast-Item.h \
    Cdma2000PDU.h   \
    Cdma2000RATType.h   \
    Cdma2000SectorID.h  \
    Cdma2000HOStatus.h  \
    Cdma2000HORequiredIndication.h  \
    Cdma2000OneXSRVCCInfo.h \
    Cdma2000OneXMEID.h  \
    Cdma2000OneXMSI.h   \
    Cdma2000OneXPilot.h \
    Cdma2000OneXRAND.h  \
    Cell-Size.h \
    CellType.h  \
    CGI.h   \
    CI.h    \
    CNDomain.h  \
    CSFallbackIndicator.h   \
    CSG-Id.h    \
    CSG-IdList.h    \
    CSG-IdList-Item.h   \
    COUNTvalue.h    \
    CriticalityDiagnostics.h    \
    CriticalityDiagnostics-IE-List.h    \
    CriticalityDiagnostics-IE-Item.h    \
    DataCodingScheme.h  \
    DL-Forwarding.h \
    Direct-Forwarding-Path-Availability.h   \
    E-RABToBeModifiedListBearerModReq.h \
    E-RABToBeModifiedItemBearerModReqIEs.h  \
    E-RABToBeModifiedItemBearerModReq.h \
    E-RABReleaseListBearerRelComp.h \
    E-RABReleaseItemBearerRelCompIEs.h  \
    E-RABReleaseItemBearerRelComp.h \
    E-RABSubjecttoDataForwardingList.h  \
    E-RABDataForwardingList.h   \
    E-RABDataForwardingItemIEs.h    \
    E-RABDataForwardingItem.h   \
    E-RABToBeSetupListCtxtSUReq.h   \
    E-RABToBeSetupItemCtxtSUReqIEs.h    \
    E-RABToBeSetupItemCtxtSUReq.h   \
    E-RABSetupListBearerSURes.h \
    E-RABSetupItemBearerSUResIEs.h  \
    E-RABSetupItemBearerSURes.h \
    E-RABFailedtoSetupListHOReqAck.h    \
    E-RABFailedtoSetupItemHOReqAckIEs.h \
    E-RABFailedToSetupItemHOReqAck.h    \
    E-RABToBeSetupListBearerSUReq.h \
    E-RABToBeSetupItemBearerSUReqIEs.h  \
    E-RABToBeSetupItemBearerSUReq.h \
    E-RABAdmittedList.h \
    E-RABAdmittedItemIEs.h  \
    E-RABAdmittedItem.h \
    E-RABToBeSwitchedDLList.h   \
    E-RABToBeSwitchedDLListIEs.h    \
    E-RABToBeSwitchedDLItem.h   \
    E-RABToBeSwitchedULList.h   \
    E-RABToBeSwitchedULItemIEs.h    \
    E-RABToBeSwitchedULItem.h   \
    E-RABModifyListBearerModRes.h   \
    E-RABModifyItemBearerModResIEs.h    \
    E-RABModifyItemBearerModRes.h   \
    E-RABSetupListCtxtSURes.h   \
    E-RABSetupListCtxtSUResIEs.h    \
    E-RABSetupItemCtxtSURes.h   \
    E-RABToBeSetupListHOReq.h   \
    E-RABToBeSetupListHOReqIEs.h    \
    E-RABToBeSetupItemHOReq.h   \
    ECGIList.h  \
    EmergencyAreaIDList.h   \
    EmergencyAreaID.h   \
    EmergencyAreaID-Broadcast.h \
    EmergencyAreaID-Broadcast-Item.h    \
    CompletedCellinEAI.h    \
    CompletedCellinEAI-Item.h   \
    ENB-ID.h    \
    GERAN-Cell-ID.h \
    Global-ENB-ID.h \
    ENB-StatusTransfer-TransparentContainer.h   \
    ENB-UE-S1AP-ID.h    \
    ENBname.h   \
    ENBX2TLAs.h \
    EncryptionAlgorithms.h  \
    EPLMNs.h    \
    EventType.h \
    E-RAB-ID.h  \
    E-RABInformationList.h  \
    E-RABInformationListItem.h  \
    E-RABList.h \
    E-RABItem.h \
    E-RABLevelQoSParameters.h   \
    EUTRAN-CGI.h    \
    ExtendedRNC-ID.h    \
    ForbiddenInterRATs.h    \
    ForbiddenTAs.h  \
    ForbiddenTAs-Item.h \
    ForbiddenTACs.h \
    ForbiddenLAs.h  \
    ForbiddenLAs-Item.h \
    ForbiddenLACs.h \
    GBR-QosInformation.h    \
    GTP-TEID.h  \
    GUMMEI.h    \
    HandoverRestrictionList.h   \
    HandoverType.h  \
    HFN.h   \
    HandoverNotify.h    \
    Inter-SystemInformationTransferType.h   \
    IMSI.h  \
    IntegrityProtectionAlgorithms.h \
    InterfacesToTrace.h \
    LAC.h   \
    LAI.h   \
    LastVisitedCell-Item.h  \
    LastVisitedEUTRANCellInformation.h  \
    LastVisitedUTRANCellInformation.h   \
    LastVisitedGERANCellInformation.h   \
    L3-Information.h    \
    MessageIdentifier.h \
    MMEname.h   \
    MME-Group-ID.h  \
    MME-Code.h  \
    MME-UE-S1AP-ID.h    \
    M-TMSI.h    \
    MSClassmark2.h  \
    MSClassmark3.h  \
    NAS-PDU.h   \
    NASSecurityParametersfromE-UTRAN.h  \
    NASSecurityParameterstoE-UTRAN.h    \
    NumberofBroadcastRequest.h  \
    NumberOfBroadcasts.h \
    OldBSS-ToNewBSS-Information.h   \
    OverloadAction.h    \
    OverloadResponse.h  \
    PagingDRX.h \
    PDCP-SN.h   \
    PLMNidentity.h  \
    Pre-emptionCapability.h \
    Pre-emptionVulnerability.h  \
    PriorityLevel.h \
    QCI.h   \
    ReceiveStatusofULPDCPSDUs.h \
    RelativeMMECapacity.h   \
    RAC.h   \
    RequestType.h   \
    ResetType.h \
    ResetAll.h  \
    RIMTransfer.h   \
    RIMInformation.h    \
    RIMRoutingAddress.h \
    ReportArea.h    \
    RepetitionPeriod.h  \
    RNC-ID.h    \
    RRC-Container.h \
    RRC-Establishment-Cause.h   \
    SecurityKey.h   \
    SecurityContext.h   \
    SerialNumber.h  \
    SONInformation.h    \
    SONInformationRequest.h \
    SONInformationReply.h   \
    SONConfigurationTransfer.h  \
    Source-ToTarget-TransparentContainer.h  \
    SourceBSS-ToTargetBSS-TransparentContainer.h    \
    SourceeNB-ID.h  \
    SRVCCOperationPossible.h    \
    SRVCCHOIndication.h \
    SourceeNB-ToTargeteNB-TransparentContainer.h    \
    SourceRNC-ToTargetRNC-TransparentContainer.h    \
    ServedGUMMEIs.h \
    ServedGUMMEIsItem.h \
    ServedGroupIDs.h    \
    ServedMMECs.h   \
    ServedPLMNs.h   \
    SubscriberProfileIDforRFP.h \
    SupportedTAs.h  \
    SupportedTAs-Item.h \
    S-TMSI.h    \
    TAC.h   \
    TAIListforWarning.h \
    TAIList.h   \
    TAIItem.h   \
    TAI.h   \
    TAI-Broadcast.h \
    TAI-Broadcast-Item.h    \
    CompletedCellinTAI.h    \
    CompletedCellinTAI-Item.h   \
    TBCD-STRING.h   \
    TargetID.h  \
    TargeteNB-ID.h  \
    TargetRNC-ID.h  \
    TargeteNB-ToSourceeNB-TransparentContainer.h    \
    Target-ToSource-TransparentContainer.h  \
    TargetRNC-ToSourceRNC-TransparentContainer.h    \
    TargetBSS-ToSourceBSS-TransparentContainer.h    \
    TimeToWait.h    \
    Time-UE-StayedInCell.h  \
    TransportLayerAddress.h \
    TraceActivation.h   \
    TraceDepth.h    \
    E-UTRAN-Trace-ID.h  \
    TypeOfError.h   \
    UEAggregateMaximumBitrate.h \
    UE-S1AP-IDs.h   \
    UE-S1AP-ID-pair.h   \
    UE-associatedLogicalS1-ConnectionListRes.h  \
    UE-associatedLogicalS1-ConnectionListResAck.h   \
    UE-associatedLogicalS1-ConnectionItem.h \
    UEIdentityIndexValue.h  \
    UE-HistoryInformation.h \
    UEPagingID.h    \
    UERadioCapability.h \
    UESecurityCapabilities.h    \
    WarningAreaList.h   \
    WarningType.h   \
    WarningSecurityInfo.h   \
    WarningMessageContents.h    \
    X2TNLConfigurationInfo.h    \
    S1AP-PDU.h  \
    InitiatingMessage.h \
    SuccessfulOutcome.h \
    UnsuccessfulOutcome.h   \
    HandoverRequired.h  \
    HandoverCommand.h   \
    HandoverPreparationFailure.h    \
    HandoverRequest.h   \
    HandoverRequestAcknowledge.h    \
    HandoverFailure.h   \
    HandoverNotify.h \
    PathSwitchRequest.h \
    PathSwitchRequestAcknowledge.h  \
    PathSwitchRequestFailure.h  \
    E-RABSetupRequest.h \
    E-RABSetupResponse.h    \
    E-RABModifyRequest.h    \
    E-RABModifyResponse.h   \
    E-RABReleaseIndication.h    \
    E-RABReleaseCommand.h   \
    E-RABReleaseResponse.h  \
    InitialContextSetupRequest.h    \
    InitialContextSetupResponse.h   \
    InitialContextSetupFailure.h    \
    UEContextReleaseRequest.h   \
    Paging.h    \
    DownlinkNASTransport.h  \
    InitialUEMessage.h  \
    UplinkNASTransport.h    \
    NASNonDeliveryIndication.h  \
    HandoverCancel.h    \
    HandoverCancelAcknowledge.h \
    Reset.h \
    ResetAcknowledge.h  \
    S1SetupResponse.h   \
    S1SetupRequest.h    \
    S1SetupFailure.h    \
    ErrorIndication.h   \
    ENBConfigurationUpdate.h    \
    ENBConfigurationUpdateAcknowledge.h \
    ENBConfigurationUpdateFailure.h \
    MMEConfigurationUpdate.h    \
    MMEConfigurationUpdateAcknowledge.h \
    MMEConfigurationUpdateFailure.h \
    DownlinkS1cdma2000tunneling.h   \
    UplinkS1cdma2000tunneling.h \
    UEContextModificationRequest.h  \
    UEContextModificationResponse.h \
    UEContextModificationFailure.h  \
    UECapabilityInfoIndication.h    \
    UEContextReleaseCommand.h   \
    UEContextReleaseComplete.h  \
    ENBStatusTransfer.h \
    MMEStatusTransfer.h \
    DeactivateTrace.h   \
    TraceStart.h    \
    TraceFailureIndication.h    \
    CellTrafficTrace.h  \
    LocationReportingControl.h  \
    LocationReportingFailureIndication.h    \
    LocationReport.h    \
    OverloadStart.h \
    OverloadStop.h  \
    WriteReplaceWarningRequest.h    \
    WriteReplaceWarningResponse.h   \
    ENBDirectInformationTransfer.h  \
    MMEDirectInformationTransfer.h  \
    ENBConfigurationTransfer.h  \
    MMEConfigurationTransfer.h  \
    PrivateMessage.h    \
    IE.h

ifdef UPDATE_RELEASE_9
S1AP_ASN_MODULE_SOURCES += \
    KillResponse.o  \
    KillRequest.o   \
    Data-Forwarding-Not-Possible.o  \
    DownlinkUEAssociatedLPPaTransport.o \
    UplinkUEAssociatedLPPaTransport.o   \
    DownlinkNonUEAssociatedLPPaTransport.o  \
    UplinkNonUEAssociatedLPPaTransport.o    \
    TAI-Cancelled.o \
    TAI-Cancelled-Item.o    \
    StratumLevel.o  \
    SynchronizationStatus.o \
    TimeSynchronizationInfo.o   \
    Routing-ID.o    \
    PS-ServiceNotAvailable.o    \
    LPPa-PDU.o  \
    ExtendedRepetitionPeriod.o  \
    EUTRANRoundTripDelayEstimationInfo.o    \
    EmergencyAreaID-Cancelled.o \
    EmergencyAreaID-Cancelled-Item.o    \
    CSGMembershipStatus.o   \
    ConcurrentWarningMessageIndicator.o \
    CellID-Cancelled.o  \
    CellID-Cancelled-Item.o \
    CellAccessMode.o    \
    CancelledCellinEAI.o    \
    CancelledCellinEAI-Item.o   \
    CancelledCellinTAI.o    \
    CancelledCellinTAI-Item.o   \
    BroadcastCancelledAreaList.o

S1AP_ASN_MODULE_HEADERS += \
    BroadcastCancelledAreaList.h    \
    CancelledCellinEAI.h    \
    CancelledCellinEAI-Item.h   \
    CancelledCellinTAI.h    \
    CancelledCellinTAI-Item.h   \
    CellAccessMode.h    \
    CellID-Cancelled.h  \
    CellID-Cancelled-Item.h \
    ConcurrentWarningMessageIndicator.h \
    CSGMembershipStatus.h   \
    Data-Forwarding-Not-Possible.h  \
    EmergencyAreaID-Cancelled.h \
    EmergencyAreaID-Cancelled-Item.h    \
    E-RABList.h \
    EUTRANRoundTripDelayEstimationInfo.h    \
    ExtendedRepetitionPeriod.h  \
    LPPa-PDU.h  \
    PS-ServiceNotAvailable.h    \
    Routing-ID.h    \
    StratumLevel.h  \
    SynchronizationStatus.h \
    TimeSynchronizationInfo.h   \
    TAI-Cancelled.h \
    TAI-Cancelled-Item.h    \
    KillResponse.h  \
    KillRequest.h   \
    DownlinkUEAssociatedLPPaTransport.h \
    UplinkUEAssociatedLPPaTransport.h   \
    DownlinkNonUEAssociatedLPPaTransport.h  \
    UplinkNonUEAssociatedLPPaTransport.h
endif

S1AP_ASN_MODULE_HEADERS+=ANY.h
S1AP_ASN_MODULE_SOURCES+=ANY.o
S1AP_ASN_MODULE_HEADERS+=BOOLEAN.h
S1AP_ASN_MODULE_SOURCES+=BOOLEAN.o
S1AP_ASN_MODULE_HEADERS+=INTEGER.h
S1AP_ASN_MODULE_HEADERS+=NativeEnumerated.h
S1AP_ASN_MODULE_SOURCES+=INTEGER.o
S1AP_ASN_MODULE_HEADERS+=NULL.h
S1AP_ASN_MODULE_SOURCES+=NULL.o
S1AP_ASN_MODULE_SOURCES+=NativeEnumerated.o
S1AP_ASN_MODULE_HEADERS+=NativeInteger.h
S1AP_ASN_MODULE_SOURCES+=NativeInteger.o
S1AP_ASN_MODULE_HEADERS+=OBJECT_IDENTIFIER.h
S1AP_ASN_MODULE_SOURCES+=OBJECT_IDENTIFIER.o
S1AP_ASN_MODULE_HEADERS+=PrintableString.h
S1AP_ASN_MODULE_SOURCES+=PrintableString.o
S1AP_ASN_MODULE_HEADERS+=asn_SEQUENCE_OF.h
S1AP_ASN_MODULE_SOURCES+=asn_SEQUENCE_OF.o
S1AP_ASN_MODULE_HEADERS+=asn_SET_OF.h
S1AP_ASN_MODULE_SOURCES+=asn_SET_OF.o
S1AP_ASN_MODULE_HEADERS+=constr_CHOICE.h
S1AP_ASN_MODULE_SOURCES+=constr_CHOICE.o
S1AP_ASN_MODULE_HEADERS+=constr_SEQUENCE.h
S1AP_ASN_MODULE_SOURCES+=constr_SEQUENCE.o
S1AP_ASN_MODULE_HEADERS+=constr_SEQUENCE_OF.h
S1AP_ASN_MODULE_SOURCES+=constr_SEQUENCE_OF.o
S1AP_ASN_MODULE_HEADERS+=constr_SET_OF.h
S1AP_ASN_MODULE_SOURCES+=constr_SET_OF.o
S1AP_ASN_MODULE_HEADERS+=asn_application.h
S1AP_ASN_MODULE_HEADERS+=asn_system.h
S1AP_ASN_MODULE_HEADERS+=asn_codecs.h
S1AP_ASN_MODULE_HEADERS+=asn_internal.h
S1AP_ASN_MODULE_HEADERS+=OCTET_STRING.h
S1AP_ASN_MODULE_SOURCES+=OCTET_STRING.o
S1AP_ASN_MODULE_HEADERS+=BIT_STRING.h
S1AP_ASN_MODULE_SOURCES+=BIT_STRING.o
S1AP_ASN_MODULE_SOURCES+=asn_codecs_prim.o
S1AP_ASN_MODULE_HEADERS+=asn_codecs_prim.h
S1AP_ASN_MODULE_HEADERS+=ber_tlv_length.h
S1AP_ASN_MODULE_SOURCES+=ber_tlv_length.o
S1AP_ASN_MODULE_HEADERS+=ber_tlv_tag.h
S1AP_ASN_MODULE_SOURCES+=ber_tlv_tag.o
S1AP_ASN_MODULE_HEADERS+=ber_decoder.h
S1AP_ASN_MODULE_SOURCES+=ber_decoder.o
S1AP_ASN_MODULE_HEADERS+=der_encoder.h
S1AP_ASN_MODULE_SOURCES+=der_encoder.o
S1AP_ASN_MODULE_HEADERS+=constr_TYPE.h
S1AP_ASN_MODULE_SOURCES+=constr_TYPE.o
S1AP_ASN_MODULE_HEADERS+=constraints.h
S1AP_ASN_MODULE_SOURCES+=constraints.o
S1AP_ASN_MODULE_HEADERS+=xer_support.h
S1AP_ASN_MODULE_SOURCES+=xer_support.o
S1AP_ASN_MODULE_HEADERS+=xer_decoder.h
S1AP_ASN_MODULE_SOURCES+=xer_decoder.o
S1AP_ASN_MODULE_HEADERS+=xer_encoder.h
S1AP_ASN_MODULE_SOURCES+=xer_encoder.o
S1AP_ASN_MODULE_HEADERS+=per_support.h
S1AP_ASN_MODULE_SOURCES+=per_support.o
S1AP_ASN_MODULE_HEADERS+=per_decoder.h
S1AP_ASN_MODULE_SOURCES+=per_decoder.o
S1AP_ASN_MODULE_HEADERS+=per_encoder.h
S1AP_ASN_MODULE_SOURCES+=per_encoder.o
S1AP_ASN_MODULE_HEADERS+=per_opentype.h
S1AP_ASN_MODULE_SOURCES+=per_opentype.o