X2AP_ASN_MODULE_SOURCES=	\
	X2ap-Criticality.c	\
	X2ap-Presence.c	\
	X2ap-PrivateIE-ID.c	\
	X2ap-ProcedureCode.c	\
	X2ap-ProtocolIE-ID.c	\
	X2ap-TriggeringMessage.c	\
	X2ap-IE-Extensions.c	\
	X2ap-AS-SecurityInformation.c	\
	X2ap-AllocationAndRetentionPriority.c	\
	X2ap-ActivatedCellList.c	\
	X2ap-ActivatedCellList-Item.c	\
	X2ap-BitRate.c	\
	X2ap-BroadcastPLMNs-Item.c	\
	X2ap-CapacityValue.c	\
	X2ap-CellCapacityClassValue.c	\
	X2ap-CellToReport-List.c	\
	X2ap-CellToReport-Item.c	\
	X2ap-CellMeasurementResult-List.c	\
	X2ap-CellMeasurementResult-Item.c	\
	X2ap-ReportingPeriodicity.c	\
	X2ap-Cause.c	\
	X2ap-CauseMisc.c	\
	X2ap-CauseProtocol.c	\
	X2ap-CauseRadioNetwork.c	\
	X2ap-CauseTransport.c	\
	X2ap-Cell-Size.c	\
	X2ap-CellInformation-List.c	\
	X2ap-CellInformation-Item.c	\
	X2ap-CellType.c	\
	X2ap-CompositeAvailableCapacityGroup.c	\
	X2ap-CompositeAvailableCapacity.c	\
	X2ap-COUNTvalue.c	\
	X2ap-CriticalityDiagnostics.c	\
	X2ap-CriticalityDiagnostics-IE-List.c	\
	X2ap-CriticalityDiagnostics-IE-Elm.c	\
	X2ap-CRNTI.c	\
	X2ap-CyclicPrefixDL.c	\
	X2ap-CyclicPrefixUL.c	\
	X2ap-DeactivationIndication.c	\
	X2ap-DL-Forwarding.c	\
	X2ap-E-RABs-Admitted-List.c	\
	X2ap-E-RABs-Admitted-Item.c	\
	X2ap-E-RABs-ToBeSetup-List.c	\
	X2ap-E-RABs-ToBeSetup-Item.c	\
	X2ap-E-RABs-SubjectToStatusTransfer-List.c	\
	X2ap-E-RABs-SubjectToStatusTransfer-Item.c	\
	X2ap-EARFCN.c	\
	X2ap-FDD-Info.c	\
	X2ap-TDD-Info.c	\
	X2ap-EUTRA-Mode-Info.c	\
	X2ap-ECGI.c	\
	X2ap-ENB-ID.c	\
	X2ap-EncryptionAlgorithms.c	\
	X2ap-EPLMNs.c	\
	X2ap-E-RAB-ID.c	\
	X2ap-E-RAB-Level-QoS-Parameters.c	\
	X2ap-E-RAB-List.c	\
	X2ap-E-RAB-Item.c	\
	X2ap-EUTRANCellIdentifier.c	\
	X2ap-EUTRANTraceID.c	\
	X2ap-EventType.c	\
	X2ap-ForbiddenInterRATs.c	\
	X2ap-ForbiddenTAs.c	\
	X2ap-ForbiddenTAs-Item.c	\
	X2ap-ForbiddenTACs.c	\
	X2ap-ForbiddenLAs.c	\
	X2ap-ForbiddenLAs-Item.c	\
	X2ap-ForbiddenLACs.c	\
	X2ap-Fourframes.c	\
	X2ap-GBR-QosInformation.c	\
	X2ap-GlobalENB-ID.c	\
	X2ap-GTPtunnelEndpoint.c	\
	X2ap-GTP-TEI.c	\
	X2ap-GUGroupIDList.c	\
	X2ap-GU-Group-ID.c	\
	X2ap-GUMMEI.c	\
	X2ap-HandoverReportType.c	\
	X2ap-HandoverRestrictionList.c	\
	X2ap-HFN.c	\
	X2ap-HWLoadIndicator.c	\
	X2ap-IntegrityProtectionAlgorithms.c	\
	X2ap-InterfacesToTrace.c	\
	X2ap-Key-eNodeB-Star.c	\
	X2ap-LAC.c	\
	X2ap-LastVisitedCell-Item.c	\
	X2ap-LastVisitedEUTRANCellInformation.c	\
	X2ap-LastVisitedUTRANCellInformation.c	\
	X2ap-LastVisitedGERANCellInformation.c	\
	X2ap-LoadIndicator.c	\
	X2ap-LocationReportingInformation.c	\
	X2ap-MME-Group-ID.c	\
	X2ap-MME-Code.c	\
	X2ap-Measurement-ID.c	\
	X2ap-MBSFN-Subframe-Infolist.c	\
	X2ap-MBSFN-Subframe-Info.c	\
	X2ap-MobilityParametersModificationRange.c	\
	X2ap-MobilityParametersInformation.c	\
	X2ap-Neighbour-Information.c	\
	X2ap-Neighbour-Information-Elm.c	\
	X2ap-NextHopChainingCount.c	\
	X2ap-Number-of-Antennaports.c	\
	X2ap-Oneframe.c	\
	X2ap-PDCP-SN.c	\
	X2ap-PCI.c	\
	X2ap-PLMN-Identity.c	\
	X2ap-PRACH-Configuration.c	\
	X2ap-Pre-emptionCapability.c	\
	X2ap-Pre-emptionVulnerability.c	\
	X2ap-PriorityLevel.c	\
	X2ap-QCI.c	\
	X2ap-ReceiveStatusofULPDCPSDUs.c	\
	X2ap-Registration-Request.c	\
	X2ap-RelativeNarrowbandTxPower.c	\
	X2ap-ReportArea.c	\
	X2ap-ReportCharacteristics.c	\
	X2ap-RNTP-Threshold.c	\
	X2ap-RRC-Context.c	\
	X2ap-RadioResourceStatus.c	\
	X2ap-DL-GBR-PRB-usage.c	\
	X2ap-UL-GBR-PRB-usage.c	\
	X2ap-DL-non-GBR-PRB-usage.c	\
	X2ap-UL-non-GBR-PRB-usage.c	\
	X2ap-DL-Total-PRB-usage.c	\
	X2ap-UL-Total-PRB-usage.c	\
	X2ap-RadioframeAllocationPeriod.c	\
	X2ap-RadioframeAllocationOffset.c	\
	X2ap-S1TNLLoadIndicator.c	\
	X2ap-ServedCellsToActivate.c	\
	X2ap-ServedCellsToActivate-Item.c	\
	X2ap-ServedCellsToModify.c	\
	X2ap-ServedCellsToModify-Item.c	\
	X2ap-Old-ECGIs.c	\
	X2ap-ServedCells.c	\
	X2ap-ServedCellItem.c	\
	X2ap-ServedCell-Information.c	\
	X2ap-ShortMAC-I.c	\
	X2ap-SRVCCOperationPossible.c	\
	X2ap-SubframeAssignment.c	\
	X2ap-SpecialSubframe-Info.c	\
	X2ap-SpecialSubframePatterns.c	\
	X2ap-SubscriberProfileIDforRFP.c	\
	X2ap-SubframeAllocation.c	\
	X2ap-TAC.c	\
	X2ap-TargeteNBtoSource-eNBTransparentContainer.c	\
	X2ap-TimeToWait.c	\
	X2ap-Time-UE-StayedInCell.c	\
	X2ap-TraceActivation.c	\
	X2ap-TraceCollectionEntityIPAddress.c	\
	X2ap-TraceDepth.c	\
	X2ap-Transmission-Bandwidth.c	\
	X2ap-TransportLayerAddress.c	\
	X2ap-TypeOfError.c	\
	X2ap-UE-HistoryInformation.c	\
	X2ap-UE-S1AP-ID.c	\
	X2ap-UE-X2AP-ID.c	\
	X2ap-UEAggregateMaximumBitRate.c	\
	X2ap-UESecurityCapabilities.c	\
	X2ap-UE-ContextInformation.c	\
	X2ap-UL-InterferenceOverloadIndication.c	\
	X2ap-UL-InterferenceOverloadIndication-Item.c	\
	X2ap-UL-HighInterferenceIndicationInfo.c	\
	X2ap-UL-HighInterferenceIndicationInfo-Item.c	\
	X2ap-UL-HighInterferenceIndication.c	\
	X2ap-UE-RLF-Report-Container.c	\
	X2ap-IE.c	\
	X2AP-PDU.c	\
	X2ap-InitiatingMessage.c	\
	X2ap-SuccessfulOutcome.c	\
	X2ap-UnsuccessfulOutcome.c	\
	X2ap-HandoverRequest.c	\
	X2ap-HandoverRequestAcknowledge.c	\
	X2ap-HandoverPreparationFailure.c	\
	X2ap-SNStatusTransfer.c	\
	X2ap-UEContextRelease.c	\
	X2ap-HandoverCancel.c	\
	X2ap-HandoverReport.c	\
	X2ap-ErrorIndication.c	\
	X2ap-ResetRequest.c	\
	X2ap-ResetResponse.c	\
	X2ap-X2SetupRequest.c	\
	X2ap-X2SetupResponse.c	\
	X2ap-X2SetupFailure.c	\
	X2ap-LoadInformation.c	\
	X2ap-ENBConfigurationUpdate.c	\
	X2ap-ENBConfigurationUpdateAcknowledge.c	\
	X2ap-ENBConfigurationUpdateFailure.c	\
	X2ap-ResourceStatusRequest.c	\
	X2ap-ResourceStatusResponse.c	\
	X2ap-ResourceStatusFailure.c	\
	X2ap-ResourceStatusUpdate.c	\
	X2ap-RLFIndication.c	\
	X2ap-PrivateMessage.c	\
	X2ap-MobilityChangeRequest.c	\
	X2ap-MobilityChangeAcknowledge.c	\
	X2ap-MobilityChangeFailure.c	\
	X2ap-CellActivationRequest.c	\
	X2ap-CellActivationResponse.c	\
	X2ap-CellActivationFailure.c

X2AP_ASN_MODULE_HEADERS=	\
	X2ap-Criticality.h	\
	X2ap-Presence.h	\
	X2ap-PrivateIE-ID.h	\
	X2ap-ProcedureCode.h	\
	X2ap-ProtocolIE-ID.h	\
	X2ap-TriggeringMessage.h	\
	X2ap-IE-Extensions.h	\
	X2ap-AS-SecurityInformation.h	\
	X2ap-AllocationAndRetentionPriority.h	\
	X2ap-ActivatedCellList.h	\
	X2ap-ActivatedCellList-Item.h	\
	X2ap-BitRate.h	\
	X2ap-BroadcastPLMNs-Item.h	\
	X2ap-CapacityValue.h	\
	X2ap-CellCapacityClassValue.h	\
	X2ap-CellToReport-List.h	\
	X2ap-CellToReport-Item.h	\
	X2ap-CellMeasurementResult-List.h	\
	X2ap-CellMeasurementResult-Item.h	\
	X2ap-ReportingPeriodicity.h	\
	X2ap-Cause.h	\
	X2ap-CauseMisc.h	\
	X2ap-CauseProtocol.h	\
	X2ap-CauseRadioNetwork.h	\
	X2ap-CauseTransport.h	\
	X2ap-Cell-Size.h	\
	X2ap-CellInformation-List.h	\
	X2ap-CellInformation-Item.h	\
	X2ap-CellType.h	\
	X2ap-CompositeAvailableCapacityGroup.h	\
	X2ap-CompositeAvailableCapacity.h	\
	X2ap-COUNTvalue.h	\
	X2ap-CriticalityDiagnostics.h	\
	X2ap-CriticalityDiagnostics-IE-List.h	\
	X2ap-CriticalityDiagnostics-IE-Elm.h	\
	X2ap-CRNTI.h	\
	X2ap-CyclicPrefixDL.h	\
	X2ap-CyclicPrefixUL.h	\
	X2ap-DeactivationIndication.h	\
	X2ap-DL-Forwarding.h	\
	X2ap-E-RABs-Admitted-List.h	\
	X2ap-E-RABs-Admitted-Item.h	\
	X2ap-E-RABs-ToBeSetup-List.h	\
	X2ap-E-RABs-ToBeSetup-Item.h	\
	X2ap-E-RABs-SubjectToStatusTransfer-List.h	\
	X2ap-E-RABs-SubjectToStatusTransfer-Item.h	\
	X2ap-EARFCN.h	\
	X2ap-FDD-Info.h	\
	X2ap-TDD-Info.h	\
	X2ap-EUTRA-Mode-Info.h	\
	X2ap-ECGI.h	\
	X2ap-ENB-ID.h	\
	X2ap-EncryptionAlgorithms.h	\
	X2ap-EPLMNs.h	\
	X2ap-E-RAB-ID.h	\
	X2ap-E-RAB-Level-QoS-Parameters.h	\
	X2ap-E-RAB-List.h	\
	X2ap-E-RAB-Item.h	\
	X2ap-EUTRANCellIdentifier.h	\
	X2ap-EUTRANTraceID.h	\
	X2ap-EventType.h	\
	X2ap-ForbiddenInterRATs.h	\
	X2ap-ForbiddenTAs.h	\
	X2ap-ForbiddenTAs-Item.h	\
	X2ap-ForbiddenTACs.h	\
	X2ap-ForbiddenLAs.h	\
	X2ap-ForbiddenLAs-Item.h	\
	X2ap-ForbiddenLACs.h	\
	X2ap-Fourframes.h	\
	X2ap-GBR-QosInformation.h	\
	X2ap-GlobalENB-ID.h	\
	X2ap-GTPtunnelEndpoint.h	\
	X2ap-GTP-TEI.h	\
	X2ap-GUGroupIDList.h	\
	X2ap-GU-Group-ID.h	\
	X2ap-GUMMEI.h	\
	X2ap-HandoverReportType.h	\
	X2ap-HandoverRestrictionList.h	\
	X2ap-HFN.h	\
	X2ap-HWLoadIndicator.h	\
	X2ap-IntegrityProtectionAlgorithms.h	\
	X2ap-InterfacesToTrace.h	\
	X2ap-Key-eNodeB-Star.h	\
	X2ap-LAC.h	\
	X2ap-LastVisitedCell-Item.h	\
	X2ap-LastVisitedEUTRANCellInformation.h	\
	X2ap-LastVisitedUTRANCellInformation.h	\
	X2ap-LastVisitedGERANCellInformation.h	\
	X2ap-LoadIndicator.h	\
	X2ap-LocationReportingInformation.h	\
	X2ap-MME-Group-ID.h	\
	X2ap-MME-Code.h	\
	X2ap-Measurement-ID.h	\
	X2ap-MBSFN-Subframe-Infolist.h	\
	X2ap-MBSFN-Subframe-Info.h	\
	X2ap-MobilityParametersModificationRange.h	\
	X2ap-MobilityParametersInformation.h	\
	X2ap-Neighbour-Information.h	\
	X2ap-Neighbour-Information-Elm.h	\
	X2ap-NextHopChainingCount.h	\
	X2ap-Number-of-Antennaports.h	\
	X2ap-Oneframe.h	\
	X2ap-PDCP-SN.h	\
	X2ap-PCI.h	\
	X2ap-PLMN-Identity.h	\
	X2ap-PRACH-Configuration.h	\
	X2ap-Pre-emptionCapability.h	\
	X2ap-Pre-emptionVulnerability.h	\
	X2ap-PriorityLevel.h	\
	X2ap-QCI.h	\
	X2ap-ReceiveStatusofULPDCPSDUs.h	\
	X2ap-Registration-Request.h	\
	X2ap-RelativeNarrowbandTxPower.h	\
	X2ap-ReportArea.h	\
	X2ap-ReportCharacteristics.h	\
	X2ap-RNTP-Threshold.h	\
	X2ap-RRC-Context.h	\
	X2ap-RadioResourceStatus.h	\
	X2ap-DL-GBR-PRB-usage.h	\
	X2ap-UL-GBR-PRB-usage.h	\
	X2ap-DL-non-GBR-PRB-usage.h	\
	X2ap-UL-non-GBR-PRB-usage.h	\
	X2ap-DL-Total-PRB-usage.h	\
	vUL-Total-PRB-usage.h	\
	X2ap-RadioframeAllocationPeriod.h	\
	X2ap-RadioframeAllocationOffset.h	\
	X2ap-S1TNLLoadIndicator.h	\
	X2ap-ServedCellsToActivate.h	\
	X2ap-ServedCellsToActivate-Item.h	\
	X2ap-ServedCellsToModify.h	\
	X2ap-ServedCellsToModify-Item.h	\
	X2ap-Old-ECGIs.h	\
	X2ap-ServedCells.h	\
	X2ap-ServedCellItem.h	\
	X2ap-ServedCell-Information.h	\
	X2ap-ShortMAC-I.h	\
	X2ap-SRVCCOperationPossible.h	\
	X2ap-SubframeAssignment.h	\
	X2ap-SpecialSubframe-Info.h	\
	X2ap-SpecialSubframePatterns.h	\
	X2ap-SubscriberProfileIDforRFP.h	\
	X2ap-SubframeAllocation.h	\
	X2ap-TAC.h	\
	X2ap-TargeteNBtoSource-eNBTransparentContainer.h	\
	X2ap-TimeToWait.h	\
	X2ap-Time-UE-StayedInCell.h	\
	X2ap-TraceActivation.h	\
	X2ap-TraceCollectionEntityIPAddress.h	\
	X2ap-TraceDepth.h	\
	X2ap-Transmission-Bandwidth.h	\
	X2ap-TransportLayerAddress.h	\
	X2ap-TypeOfError.h	\
	X2ap-UE-HistoryInformation.h	\
	X2ap-UE-S1AP-ID.h	\
	X2ap-UE-X2AP-ID.h	\
	X2ap-UEAggregateMaximumBitRate.h	\
	X2ap-UESecurityCapabilities.h	\
	X2ap-UE-ContextInformation.h	\
	X2ap-UL-InterferenceOverloadIndication.h	\
	X2ap-UL-InterferenceOverloadIndication-Item.h	\
	X2ap-UL-HighInterferenceIndicationInfo.h	\
	X2ap-UL-HighInterferenceIndicationInfo-Item.h	\
	X2ap-UL-HighInterferenceIndication.h	\
	X2ap-UE-RLF-Report-Container.h	\
	X2ap-IE.h	\
	X2ap-X2AP-PDU.h	\
	X2ap-InitiatingMessage.h	\
	X2ap-SuccessfulOutcome.h	\
	X2ap-UnsuccessfulOutcome.h	\
	X2ap-HandoverRequest.h	\
	X2ap-HandoverRequestAcknowledge.h	\
	X2ap-HandoverPreparationFailure.h	\
	X2ap-SNStatusTransfer.h	\
	X2ap-UEContextRelease.h	\
	X2ap-HandoverCancel.h	\
	X2ap-HandoverReport.h	\
	X2ap-ErrorIndication.h	\
	X2ap-ResetRequest.h	\
	X2ap-ResetResponse.h	\
	X2ap-X2SetupRequest.h	\
	X2ap-X2SetupResponse.h	\
	X2ap-X2SetupFailure.h	\
	X2ap-LoadInformation.h	\
	X2ap-ENBConfigurationUpdate.h	\
	X2ap-ENBConfigurationUpdateAcknowledge.h	\
	X2ap-ENBConfigurationUpdateFailure.h	\
	X2ap-ResourceStatusRequest.h	\
	X2ap-ResourceStatusResponse.h	\
	X2ap-ResourceStatusFailure.h	\
	X2ap-ResourceStatusUpdate.h	\
	X2ap-RLFIndication.h	\
	X2ap-PrivateMessage.h	\
	X2ap-MobilityChangeRequest.h	\
	X2ap-MobilityChangeAcknowledge.h	\
	X2ap-MobilityChangeFailure.h	\
	X2ap-CellActivationRequest.h	\
	X2ap-CellActivationResponse.h	\
	X2ap-CellActivationFailure.h

X2AP_ASN_MODULE_HEADERS+=ANY.h
X2AP_ASN_MODULE_SOURCES+=ANY.o
X2AP_ASN_MODULE_HEADERS+=BOOLEAN.h
X2AP_ASN_MODULE_SOURCES+=BOOLEAN.o
X2AP_ASN_MODULE_HEADERS+=INTEGER.h
X2AP_ASN_MODULE_HEADERS+=NativeEnumerated.h
X2AP_ASN_MODULE_SOURCES+=INTEGER.o
X2AP_ASN_MODULE_HEADERS+=NULL.h
X2AP_ASN_MODULE_SOURCES+=NULL.o
X2AP_ASN_MODULE_SOURCES+=NativeEnumerated.o
X2AP_ASN_MODULE_HEADERS+=NativeInteger.h
X2AP_ASN_MODULE_SOURCES+=NativeInteger.o
X2AP_ASN_MODULE_HEADERS+=OBJECT_IDENTIFIER.h
X2AP_ASN_MODULE_SOURCES+=OBJECT_IDENTIFIER.o
X2AP_ASN_MODULE_HEADERS+=asn_SEQUENCE_OF.h
X2AP_ASN_MODULE_SOURCES+=asn_SEQUENCE_OF.o
X2AP_ASN_MODULE_HEADERS+=asn_SET_OF.h
X2AP_ASN_MODULE_SOURCES+=asn_SET_OF.o
X2AP_ASN_MODULE_HEADERS+=constr_CHOICE.h
X2AP_ASN_MODULE_SOURCES+=constr_CHOICE.o
X2AP_ASN_MODULE_HEADERS+=constr_SEQUENCE.h
X2AP_ASN_MODULE_SOURCES+=constr_SEQUENCE.o
X2AP_ASN_MODULE_HEADERS+=constr_SEQUENCE_OF.h
X2AP_ASN_MODULE_SOURCES+=constr_SEQUENCE_OF.o
X2AP_ASN_MODULE_HEADERS+=constr_SET_OF.h
X2AP_ASN_MODULE_SOURCES+=constr_SET_OF.o
X2AP_ASN_MODULE_HEADERS+=asn_application.h
X2AP_ASN_MODULE_HEADERS+=asn_system.h
X2AP_ASN_MODULE_HEADERS+=asn_codecs.h
X2AP_ASN_MODULE_HEADERS+=asn_internal.h
X2AP_ASN_MODULE_HEADERS+=OCTET_STRING.h
X2AP_ASN_MODULE_SOURCES+=OCTET_STRING.o
X2AP_ASN_MODULE_HEADERS+=BIT_STRING.h
X2AP_ASN_MODULE_SOURCES+=BIT_STRING.o
X2AP_ASN_MODULE_SOURCES+=asn_codecs_prim.o
X2AP_ASN_MODULE_HEADERS+=asn_codecs_prim.h
X2AP_ASN_MODULE_HEADERS+=ber_tlv_length.h
X2AP_ASN_MODULE_SOURCES+=ber_tlv_length.o
X2AP_ASN_MODULE_HEADERS+=ber_tlv_tag.h
X2AP_ASN_MODULE_SOURCES+=ber_tlv_tag.o
X2AP_ASN_MODULE_HEADERS+=ber_decoder.h
X2AP_ASN_MODULE_SOURCES+=ber_decoder.o
X2AP_ASN_MODULE_HEADERS+=der_encoder.h
X2AP_ASN_MODULE_SOURCES+=der_encoder.o
X2AP_ASN_MODULE_HEADERS+=constr_TYPE.h
X2AP_ASN_MODULE_SOURCES+=constr_TYPE.o
X2AP_ASN_MODULE_HEADERS+=constraints.h
X2AP_ASN_MODULE_SOURCES+=constraints.o
X2AP_ASN_MODULE_HEADERS+=xer_support.h
X2AP_ASN_MODULE_SOURCES+=xer_support.o
X2AP_ASN_MODULE_HEADERS+=xer_decoder.h
X2AP_ASN_MODULE_SOURCES+=xer_decoder.o
X2AP_ASN_MODULE_HEADERS+=xer_encoder.h
X2AP_ASN_MODULE_SOURCES+=xer_encoder.o
X2AP_ASN_MODULE_HEADERS+=per_support.h
X2AP_ASN_MODULE_SOURCES+=per_support.o
X2AP_ASN_MODULE_HEADERS+=per_decoder.h
X2AP_ASN_MODULE_SOURCES+=per_decoder.o
X2AP_ASN_MODULE_HEADERS+=per_encoder.h
X2AP_ASN_MODULE_SOURCES+=per_encoder.o
X2AP_ASN_MODULE_HEADERS+=per_opentype.h
X2AP_ASN_MODULE_SOURCES+=per_opentype.o
