eNB_id0_an0_srs_ch_est;
eNB_id0_an1_srs_ch_est;
eNB_id1_an0_srs_ch_est;
eNB_id1_an1_srs_ch_est;
eNB_id2_an0_srs_ch_est;
eNB_id2_an1_srs_ch_est;

figure(6)
subplot(3,2,1);
plot(abs(eNB0_0_srs_ch_est));
subplot(3,2,2);
plot(abs(eNB0_1_srs_ch_est));
subplot(3,2,3);
plot(abs(eNB1_0_srs_ch_est));
subplot(3,2,4);
plot(abs(eNB1_1_srs_ch_est));
subplot(3,2,5);
plot(abs(eNB2_0_srs_ch_est));
subplot(3,2,6);
plot(abs(eNB2_1_srs_ch_est));